import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {existsSync} from 'node:fs';
const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||(existsSync('/snap/bin/chromium')?'/snap/bin/chromium':undefined),args:['--no-sandbox']});
const context=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await context.newPage();const requests=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const t={id:'fake-thread',title:'Menu test thread',projectId:'p',providerId:'codex',status:'idle',unread:true,pinnedAt:null,updatedAt:Date.now(),labels:[]};
await p.route('**/api/**',async r=>{const path=new URL(r.request().url()).pathname;let json={};if(path==='/api/meta')json={projects:[{id:'p',name:'Test'}],taskProjects:[],labels:[],bbUrl:'https://bb.example'};else if(path==='/api/usage')json={providers:{},syncedAt:Date.now()};else if(path==='/api/threads')json={threads:[t],total:1,nextOffset:null};else if(path.endsWith('/menu'))json={thread:t,localLink:'http://127.0.0.1:38886/projects/p/threads/fake-thread',cloudLink:'https://bb.example/projects/p/threads/fake-thread'};else if(path.endsWith('/action')){const input=r.request().postDataJSON();requests.push(input);json={result:input.action==='children'?{nonDeletedChildCount:2}:input.action==='split'?{delivered:0}:{}};if(input.action==='pin')t.pinnedAt=123;if(input.action==='rename')t.title=input.title;}else throw Error('Unexpected request '+path);await r.fulfill({json})});
try{
 await p.goto(process.env.POCKET_TEST_URL||'http://127.0.0.1:8890');const row=p.locator('[data-thread-card]');const more=p.locator('[data-thread-menu]');await more.click();await p.locator('[data-thread-action="pin"]').waitFor();assert.equal(await p.locator('.threadview').count(),0);
 assert.deepEqual((await p.locator('[data-thread-action]').evaluateAll(es=>es.map(e=>e.dataset.threadAction))).sort(),['split','copy-id','copy-local','copy-cloud','read','pin','rename','archive','delete'].sort());
 await p.locator('[data-thread-action="pin"]').click();await p.waitForFunction(()=>!document.querySelector('#sheet').open);assert.equal(requests.at(-1).action,'pin');await more.click();await p.locator('[data-thread-action="unpin"]').waitFor();await p.getByRole('button',{name:'Close',exact:true}).click();
 await row.dispatchEvent('pointerdown',{button:0,isPrimary:true,pointerType:'touch',clientX:50,clientY:150});await p.waitForTimeout(650);await row.dispatchEvent('pointerup',{button:0,isPrimary:true,pointerType:'touch'});await p.locator('[data-thread-action="rename"]').waitFor();assert.equal(await p.locator('.threadview').count(),0);
 await p.locator('[data-thread-action="rename"]').click();await p.locator('#thread-name').fill('New title');await p.getByRole('button',{name:'Save name',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('#sheet').open);assert.deepEqual(requests.at(-1),{action:'rename',title:'New title'});
 await p.waitForTimeout(1000);await row.dispatchEvent('pointerdown',{button:0,isPrimary:true,pointerType:'touch',clientX:50,clientY:150});await row.dispatchEvent('pointermove',{clientX:50,clientY:180});await p.waitForTimeout(650);await row.dispatchEvent('pointerup',{});assert.equal(await p.locator('#sheet').evaluate(e=>e.open),false);
 await row.dispatchEvent('contextmenu',{bubbles:true,button:2});await p.locator('[data-thread-action="delete"]').click();await p.locator('#confirm-children').waitFor();assert.equal(requests.filter(r=>r.action==='delete').length,0);await p.locator('[data-thread-action="confirm-delete"]').click();assert.equal(requests.filter(r=>r.action==='delete').length,0);await p.locator('#confirm-children').check();await p.locator('[data-thread-action="confirm-delete"]').click();await p.waitForFunction(()=>!document.querySelector('#sheet').open);assert.deepEqual(requests.at(-1),{action:'delete',confirmed:true,childThreadsConfirmed:true});
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS: overflow menu parity, current pin state, long press, scroll cancellation, rename and confirmed delete (all mocked)');
}finally{await b.close()}
