import test from 'node:test';import assert from 'node:assert/strict';import {createPocketServer} from '../bridge.mjs';import {newThreadApi} from '../new-thread.mjs';
const model={model:'m',id:'m',supportedReasoningEfforts:[{reasoningEffort:'high'}],supportedServiceTiers:[{id:'fast'}]};
const catalog={models:[model],providers:[{id:'p',available:true,capabilities:{permissionModes:['auto','full'],supportsServiceTier:true},serviceTiers:[{id:'fast'}]}],permissionCeiling:'auto'};
const payload={id:'11111111-1111-1111-1111-111111111111',projectId:'project',environmentId:'env',providerId:'p',model:'m',reasoningLevel:'high',permissionMode:'auto',serviceTier:'fast',title:'Hello',text:'Do the work'};
test('new thread validates capabilities and workspace; duplicate requests and restarts never spawn twice',async()=>{
 let calls=0,records={},routed;const api=newThreadApi({projects:{list:async()=>[{id:'project'}]},environments:{list:async()=>[{id:'env',status:'ready',lifecycle:{phase:'active'},hostLifecycle:'active'}]},providers:{models:async a=>{routed=a;return catalog}},threads:{spawn:async args=>{calls++;assert.equal(args.reasoningLevel,'high');assert.equal(args.environment.environmentId,'env');return {id:'created'}}}});
 for(const bad of [{model:'bad'},{reasoningLevel:'low'},{permissionMode:'full'},{serviceTier:'ultrafast'},{environmentId:'other'},{text:''}])await assert.rejects(()=>api.validate({...payload,...bad}));
 await api.validate(payload);assert.equal(routed.environmentId,'env');
 const options={port:18897,newThread:api,journalStore:{load:()=>records,save:r=>{records=structuredClone(r)}}};let server=await createPocketServer(options);
 const post=(body,headers={})=>fetch('http://127.0.0.1:18897/api/new-thread',{method:'POST',headers:{'content-type':'application/json','x-pocket-request':'1',...headers},body:JSON.stringify(body)});
 try{assert.equal((await post(payload,{origin:'https://evil.example'})).status,403);const results=await Promise.all([post(payload),post(payload)]);await Promise.all(results.map(r=>r.json()));assert.equal(calls,1);assert.equal((await (await post({...payload,text:'different'})).json()).error,'Creation identifier already used');await server.close();server=await createPocketServer({...options,port:18898});const result=await fetch('http://127.0.0.1:18898/api/new-thread/receipt?id='+payload.id).then(r=>r.json());assert.equal(result.threadId,'created');assert.equal(calls,1)}finally{await server.close()}
});
test('uncertain creation persists as unknown and is never retried',async()=>{let calls=0,records={};const server=await createPocketServer({port:18899,newThread:{validate:async x=>x,spawn:async()=>{calls++;throw Error('lost response')}},journalStore:{load:()=>records,save:r=>{records=r}}});try{for(let i=0;i<2;i++){const r=await fetch('http://127.0.0.1:18899/api/new-thread',{method:'POST',headers:{'content-type':'application/json','x-pocket-request':'1'},body:JSON.stringify(payload)}).then(r=>r.json());assert.equal(r.state,'unknown')}assert.equal(calls,1)}finally{await server.close()}});
