import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {existsSync} from 'node:fs';import {filterThreads} from '../src/domain.mjs';
const base=process.env.POCKET_TEST_URL||'http://127.0.0.1:8890';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||(existsSync('/snap/bin/chromium')?'/snap/bin/chromium':undefined),args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await context.newPage();const errors=[],writes=[];let offline=false;
page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
const projects=[{id:'proj_personal',kind:'personal',name:'Personal'},{id:'proj_pocket',kind:'standard',name:'Pocket'}],taskProjects=[{id:'tp',name:'Pocket',prefix:'POCKET',linkedBbProjectId:'proj_pocket'}];
const threads=[{id:'demo1',title:'Plan the mobile app',projectId:'proj_personal',providerId:'codex',status:'idle',updatedAt:Date.now(),labels:[],unread:true},{id:'demo2',title:'Fix keyboard overlap',projectId:'proj_pocket',providerId:'claude-code',status:'active',updatedAt:Date.now()-10000,labels:['design'],unread:true},{id:'demo3',title:'Automated report',projectId:'proj_pocket',providerId:'codex',status:'idle',updatedAt:Date.now()-20000,labels:['automation']}];
const providers=['codex','claude-code'].map(id=>({id,displayName:id==='codex'?'Codex':'Claude Code',available:true,capabilities:{permissionModes:['auto','full'],supportsServiceTier:true},serviceTiers:[{id:'fast',label:'Fast'}]}));
const task={id:'task1',key:'POCKET-123',projectId:'tp',title:'Review mobile keyboard',description:'Check the composer on a phone.',status:'in_progress',priority:'high',updatedAt:new Date().toISOString()};
await page.route('**/api/**',async r=>{if(offline)return r.abort();const req=r.request(),u=new URL(req.url()),path=u.pathname;let json={};if(req.method()==='POST')writes.push({path,body:path.endsWith('/attachments')?null:req.postDataJSON()});
 if(path==='/api/meta')json={projects,taskProjects,labels:[{id:'l1',slug:'automation',name:'automation'},{id:'l2',slug:'design',name:'design'}],bbUrl:base};
 else if(path==='/api/threads'){const rows=filterThreads(threads,Object.fromEntries(u.searchParams));json={threads:rows,total:rows.length,nextOffset:null,stale:false,syncedAt:Date.now()}}
 else if(path==='/api/usage')json={providers:{codex:{status:'ok',windows:[{label:'Session',usedPercent:22}]},'claude-code':{status:'ok',windows:[{label:'Current session',kind:'five-hour',usedPercent:36},{label:'Weekly limit',kind:'weekly',usedPercent:72}]}},syncedAt:Date.now()};
 else if(path==='/api/tasks')json={tasks:[task],total:1,nextOffset:null};
 else if(path==='/api/task/task1')json={task,comments:[],taskThreads:[{threadId:'demo2',title:'Fix keyboard overlap',status:'active'}]};
 else if(path==='/api/new-thread/projects')json={projects};
 else if(path==='/api/new-thread/options'){const model=u.searchParams.get('providerId')==='claude-code'?'claude-opus-5-5':'gpt-6.1-sol';json={providers,models:[{id:model,model,displayName:model,isDefault:true,defaultReasoningEffort:'medium',supportedReasoningEfforts:['medium','high'].map(reasoningEffort=>({reasoningEffort}))}],permissionCeiling:'full',environments:[{id:'env1',name:'Main workspace'}]}}
 else if(path==='/api/new-thread')json={state:'sent',threadId:'created'};
 else if(path.endsWith('/timeline')){const id=path.split('/')[3];json={thread:threads.find(t=>t.id===id)||{id,title:'Created thread',projectId:'proj_pocket',providerId:'claude-code',status:'idle'},rows:[{id:'message1',kind:'conversation',role:'assistant',text:'A demo conversation for testing.',createdAt:Date.now(),sourceSeqStart:1}],timelinePage:{hasOlderRows:false}}}
 else if(path.endsWith('/menu'))json={thread:{...threads.find(t=>t.id===path.split('/')[3]),archivedAt:null},localLink:base,cloudLink:base};
 else if(path.endsWith('/action'))json={result:req.postDataJSON().action==='children'?{nonDeletedChildCount:0}:{}};
 else if(path.endsWith('/attachments'))json={id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',name:'sample.pdf',sizeBytes:4,type:'localFile'};
 else if(path.endsWith('/send')||path.endsWith('/delivery'))json={state:'sent'};
 else if(!path.endsWith('/read')&&!path.endsWith('/stop'))throw Error('Unexpected API route '+path);
 await r.fulfill({json});
});
const choose=async(name,value)=>{const select=page.locator(`select[name="${name}"]`);if(await select.count())await select.selectOption(value);else await page.locator(`label:has(input[name="${name}"][value="${value}"])`).click()};
const close=async()=>{await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#sheet').open)};
const themeMenu=async()=>{await page.locator('[data-action="app-menu"]').click();await page.getByRole('button',{name:'Themes',exact:true}).click()};
const switchTo=async theme=>{await themeMenu();await page.locator(`[data-pocket-theme="${theme}"]`).click();await page.waitForFunction(t=>document.documentElement.dataset.theme===t,theme);await page.locator('[data-thread]').first().waitFor()};
try{
 await page.goto(base+'/#threads');await page.locator('[data-thread]').first().waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'opus');assert.equal(await page.locator('[data-thread]').count(),2);
 await page.locator('#search').fill('keyboard');await page.waitForTimeout(400);assert.equal(await page.locator('[data-thread]').count(),1);await page.locator('#search').fill('');await page.waitForTimeout(400);
 // Establish shared filters using the default layout's actual controls.
 await page.locator('[data-action="filters"]').click();await choose('project','proj_pocket');await choose('status','running');await page.locator('#filterform button[type="submit"]').click();await page.waitForTimeout(400);assert.equal(await page.locator('[data-thread]').count(),1);
 const savedFilters=await page.evaluate(()=>localStorage.getItem('pocket:filters'));
 for(const theme of ['opus','sol','astra','grok']){
  if(theme!=='opus')await switchTo(theme);
  assert.equal(await page.evaluate(()=>localStorage.getItem('pocket:filters')),savedFilters);
  await page.waitForFunction(()=>document.querySelectorAll('.usagepill b').length===3);assert.deepEqual(await page.locator('.usagepill.stacked b').allTextContents(),['64%','28%']);const text=(await page.locator('.usagepill').allTextContents()).join('').replace(/\s/g,'');assert.match(text,/^[\d%—]+$/);
  await themeMenu();assert.equal(await page.locator(`[data-pocket-theme="${theme}"]`).getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-pocket-theme]').count(),4);await close();
  // Same backend thread and same saved text/attachments through every layout.
  await page.locator('[data-thread="demo2"]').click();await page.locator('#draft').waitFor();if(theme==='opus'){await page.locator('#draft').fill('Draft shared by every theme');await page.locator('#attachfiles').setInputFiles({name:'sample.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF')});await page.locator('.draftfile').waitFor()}else{assert.equal(await page.locator('#draft').inputValue(),'Draft shared by every theme');assert.equal(await page.locator('.draftfile').count(),1)}
  await page.locator('#draft').focus();await page.evaluate(()=>{Object.defineProperty(visualViewport,'height',{configurable:true,value:420});Object.defineProperty(visualViewport,'offsetTop',{configurable:true,value:90});visualViewport.dispatchEvent(new Event('resize'));visualViewport.dispatchEvent(new Event('scroll'))});await page.waitForTimeout(150);const composer=await page.locator('.composer').boundingBox();assert(Math.abs(composer.y+composer.height-510)<3,theme+' composer bottom');await page.evaluate(()=>{delete visualViewport.height;delete visualViewport.offsetTop;visualViewport.dispatchEvent(new Event('resize'))});
  await page.goto(base+'/#threads');await page.locator('[data-thread]').first().waitFor();
  await page.locator('[data-thread-menu]').first().click();await page.locator('[data-thread-action="rename"]').waitFor();for(const action of ['rename','delete','archive','pin','read','copy-id','split'])assert.equal(await page.locator(`[data-thread-action="${action}"]`).count(),1);await close();
  const row=page.locator('[data-thread-card]').first();const rect=await row.boundingBox();await row.dispatchEvent('pointerdown',{button:0,isPrimary:true,pointerType:'touch',clientX:rect.x+60,clientY:rect.y+20});await page.waitForTimeout(650);await row.dispatchEvent('pointerup',{});await page.locator('[data-thread-action="rename"]').waitFor();await close();
  await page.goto(base+'/#tasks');await page.locator('[data-task]').first().click();await page.locator('#taskcontent').waitFor();assert.match(await page.locator('#taskcontent').innerText(),/POCKET-123/);await page.goto(base+'/#projects');await page.getByText('POCKET',{exact:true}).first().waitFor();
  await page.goto(base+'/#threads');await page.locator('[data-action="new-thread"]').first().click();await page.locator('#new-model').waitFor({state:'attached'});await page.waitForTimeout(400);
  if(theme==='opus'){await choose('providerId','claude-code');await page.waitForFunction(()=>document.querySelector('#new-model')?.value==='claude-opus-5-5');await choose('reasoningLevel','high');await choose('environmentId','env1');await page.waitForTimeout(300);await choose('providerId','claude-code');await page.waitForFunction(()=>document.querySelector('#new-model')?.value==='claude-opus-5-5');await choose('reasoningLevel','high');await page.locator('#new-title').fill('Retained title');await page.locator('#new-text').fill('Retained first message')}
  else{assert.equal(await page.locator('#new-title').inputValue(),'Retained title');assert.equal(await page.locator('#new-text').inputValue(),'Retained first message')}
  await close();await page.setViewportSize({width:320,height:700});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,theme+' horizontal overflow');await themeMenu();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await close();await page.setViewportSize({width:390,height:844});console.log('PASS '+theme+': menu, shared filters/drafts/files, tasks/projects, long press, new-thread draft, keyboard, narrow layout');
 }
 await page.waitForTimeout(1000); // Let the intentional post-long-press click guard expire.
 // Sending uses the same uploaded ID, without duplicating sends on a switch.
 await page.locator('[data-thread="demo2"]').click();await page.locator('#draft').waitFor();await page.locator('#compose button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#draft')?.value==='');assert.equal(writes.filter(w=>w.path.endsWith('/send')).length,1);assert.deepEqual(writes.find(w=>w.path.endsWith('/send')).body.attachmentIds,['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa']);
 await page.goto(base+'/#threads');await page.locator('[data-action="new-thread"]').first().click();await page.locator('#new-model').waitFor();await page.getByRole('button',{name:'Start thread',exact:true}).click();await page.waitForURL('**/#thread/created');const creation=writes.find(w=>w.path==='/api/new-thread').body;assert.equal(creation.text,'Retained first message');assert.equal(creation.title,'Retained title');
 await page.goto(base+'/#threads');await page.locator('[data-thread]').first().waitFor();await page.evaluate(async()=>await navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 const cached=await page.evaluate(async()=>{const names=await caches.keys();const cache=await caches.open(names.find(n=>n.startsWith('pocket-shell-')));return (await cache.keys()).map(r=>new URL(r.url).pathname)});for(const t of ['opus','sol','astra','grok'])assert(cached.includes('/themes/'+t+'/app.js'));
 offline=true;await context.setOffline(true);await switchTo('opus');await switchTo('sol');await page.reload();await page.locator('[data-thread]').first().waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'sol');console.log('PASS: all themes cached; offline switching and reload preserve state');
 offline=false;await context.setOffline(false);await page.evaluate(()=>localStorage.setItem('pocket:theme','"invalid"'));await page.reload();await page.locator('[data-thread]').first().waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'opus');assert.deepEqual(errors,[]);console.log('PASS: invalid preference falls back to Opus; zero JS errors; all writes mocked');
}finally{await browser.close()}
