import {openThemeMenu} from './themes.js';
import {setupNewThread} from './new-thread.js';
import {providerIcons} from './provider-icons.js';
import {marked} from 'marked';
import DOMPurify from 'dompurify';
import {get,put,read,save} from './storage.js';
import {$,esc,icon,toast,sheet,openSheet,sheetHead} from './ui.js';

const app=$('#app');
const defaults=()=>({q:'',project:'',status:'',include:'',exclude:'automation',unread:'false',sort:'recent'});
const taskDefaults=()=>({q:'',project:'',status:''});
let filters=read('filters',defaults()),taskFilters=read('taskFilters',taskDefaults());
let tab=read('tab','threads'),meta={projects:[],taskProjects:[],labels:[]},data=null,route='',threadId=null,threadData=null,olderRows=[],olderCursor=null,threadReady=false,epoch=0,connection='Connecting',connectionBad=false,error='',pollTimer,searchTimer,listScroll=0,loadingOlder=false;
let attachmentUpload=false;
let menuThread=null,menuInfo=null,menuEpoch=0,menuBusy=false;
let sharedText=read('sharedText','');
let usage=null,usageError='',usagePending=false,usageChecked=0;
let views=read('views',[]),pending=read('pending',{}),renderedRows='';
for(const p of Object.values(pending))if(p.state==='sending')p.state='unknown';

const now=()=>Date.now();
const relative=t=>{const n=Math.max(0,(now()-new Date(t).getTime())/60000);return n<1?'now':n<60?Math.floor(n)+'m':n<1440?Math.floor(n/60)+'h':n<10080?Math.floor(n/1440)+'d':new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric'})};
const bbUrl=()=>{try{const u=new URL(meta.bbUrl||location.origin);return ['http:','https:'].includes(u.protocol)?esc(u.href):'/'}catch{return '/'}};
const pname=id=>meta.projects.find(p=>p.id===id)?.name||'Personal';
const tname=id=>meta.taskProjects.find(p=>p.id===id)?.name||'Tasks';
const lname=slug=>meta.labels.find(l=>l.slug===slug)?.name||slug;
const pretty=s=>(s||'').replaceAll('_',' ');
const cap=s=>s?s[0].toUpperCase()+s.slice(1):s;
const providerName=id=>({'codex':'Codex','claude-code':'Claude','acp-cursor':'Cursor'}[id]||id||'Agent');
const providerMark=id=>providerIcons[id]||icon('bolt');
const running=s=>['active','starting','stopping'].includes(s);
const liveStatus=t=>t?.runtime?.displayStatus||t?.status;
function threadState(t){if(t.hasPendingInteraction)return ['attention','Needs input'];if(running(t.status))return ['running',t.status==='stopping'?'Stopping':'Running'];if(t.status==='error')return ['error','Error'];return [esc(t.status||'idle'),cap(pretty(t.status||'idle'))]}
function md(text){return DOMPurify.sanitize(marked.parse(text||'',{breaks:true}),{FORBID_TAGS:['style','form','input','button','iframe'],FORBID_ATTR:['style']})}

async function api(path,body,timeout=25000){const res=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json','x-pocket-request':'1'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(timeout),cache:'no-store'});if(res.redirected||!res.headers.get('content-type')?.includes('application/json'))throw new Error('Sign in to BB Connect to reconnect');const d=await res.json();if(!res.ok){const e=new Error(d.error||'Request failed');e.status=res.status;throw e;}return d}
const openNewThread=setupNewThread({api,esc,read,save,sheet,navigate,toast});

function syncText(text,isOffline=false){connection=text;connectionBad=isOffline;for(const el of document.querySelectorAll('.sync')){el.classList.toggle('offline',isOffline);el.innerHTML=`<span class="dot"></span>${esc(text)}`}renderStrip()}

/* ---------- Usage ---------- */
function usageRemaining(used){return Number.isFinite(used)?Math.max(0,Math.min(100,Math.round(100-used))):null}
function usageTone(used){const remaining=usageRemaining(used);return remaining===null?'unknown':remaining<=15?'critical':remaining<=40?'low':'ok'}
function usageProviders(){return Object.entries(usage?.providers||{}).filter(([,p])=>p.status!=='not_installed')}
function usageCounters(){
 return usageProviders().map(([id,p])=>{
  const windows=p.status==='ok'?p.windows||[]:[];
  const selected=id==='claude-code'?[windows.find(w=>w.kind==='five-hour'||/current session/i.test(w.label)),windows.find(w=>!w.model&&(w.kind==='weekly'||/^weekly limit$/i.test(w.label)))]:[windows[0]];
  const labels=id==='claude-code'?['Current session','Weekly limit']:[selected[0]?.label||'Usage'];
  const title=providerName(id)+' · '+selected.map((w,i)=>labels[i]+': '+(Number.isFinite(w?.usedPercent)?usageRemaining(w.usedPercent)+'% remaining':'unavailable')).join(' · ');
  return `<span class="usagepill ${id==='claude-code'?'stacked':''}" title="${esc(title)}" role="img" aria-label="${esc(title)}">${providerMark(id)}<span class="usagenumbers">${selected.map(w=>{const n=usageRemaining(w?.usedPercent);return `<b class="usage-${usageTone(w?.usedPercent)}">${n===null?'—':n+'%'}</b>`}).join('')}</span></span>`;
 }).join('');
}
function usageButton(){const counters=usageCounters();return `<button class="usagebar ${usage?.stale||usageError?'stale':''}" data-action="usage" aria-label="Usage limits" aria-haspopup="dialog">${counters||`<span class="usageloading">${icon('gauge')}<b class="usage-unknown">${usageError?'!':usage?'—':'…'}</b></span>`}</button>`}
function usageSheetBody(){
 const providers=usageProviders();
 return `${usageError||usage?.stale?`<p class="notice">${usage?'Saved usage · ':''}${esc(usageError||'Refreshing…')}</p>`:''}${providers.map(([id,p])=>`<section class="usagecard"><header>${providerMark(id)}<strong>${esc(providerName(id))}</strong>${p.planLabel?`<small>${esc(p.planLabel)}</small>`:''}</header>${p.status==='ok'?(p.windows?.length?p.windows.map(w=>{const n=Number.isFinite(w.usedPercent)?w.usedPercent:null;const date=w.resetsAt?new Date(w.resetsAt):null;const left=usageRemaining(n);return `<div class="usagewindow usage-${usageTone(n)}"><div class="uw-top"><span>${esc(w.label)}</span><b>${n===null?'Unknown':left+'% left'}</b></div>${n===null?'':`<div class="meter" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${left}" aria-label="${esc(providerName(id)+' '+w.label+' remaining allowance')}"><i style="width:${left}%"></i></div>`}<small>${date&&Number.isFinite(date.getTime())?'Resets '+esc(date.toLocaleString(undefined,{weekday:'short',hour:'2-digit',minute:'2-digit'})):'Reset time unavailable'}</small></div>`}).join(''):'<p class="muted">No usage windows reported.</p>'):`<p class="muted">${esc(p.status==='unauthenticated'?'Sign in through BB':p.status==='expired'?'Session expired. Sign in through BB.':'Usage unavailable')}</p>`}</section>`).join('')||(usage?'<p class="muted">No provider counters available.</p>':`<p class="muted">${usageError?'Could not fetch usage. Retry below.':'Fetching provider counters. This can take a few seconds.'}</p>`)}<p class="legend"><span class="usage-ok">● over 40%</span><span class="usage-low">● 16–40%</span><span class="usage-critical">● 15% or less</span></p><div class="sheetactions"><button class="secondary wide" data-action="usage-refresh">${icon('refresh')}Refresh usage</button>${usage?.syncedAt?`<small>Updated ${esc(new Date(usage.syncedAt).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'}))}</small>`:''}</div>`;
}
function openUsage(){openSheet(`<div class="sheetinner">${sheetHead('Remaining usage',{sub:'Allowance left in each provider window'})}<div id="usagesheet">${usageSheetBody()}</div></div>`);refreshUsage()}
function renderUsage(){const el=$('#usagepanel');if(el)el.innerHTML=usageButton();const s=$('#usagesheet');if(s&&sheet.open)s.innerHTML=usageSheetBody()}
async function refreshUsage(force=false){if(usagePending||(!force&&Date.now()-usageChecked<(usageError?15000:60000)))return;usagePending=true;usageChecked=Date.now();try{usage=await api('usage',undefined,12000);usageError=usage.warning?'BB usage unavailable':'';put('usage',usage)}catch(e){usageError=navigator.onLine?(e.name==='TimeoutError'?'Provider response is slow; retrying':e.message):'Offline';if(usage)usage.stale=true}finally{usagePending=false;renderUsage()}}

/* ---------- Share to Pocket ---------- */
function shareBanner(){return sharedText?`<div class="sharebanner"><div class="sb-head">${icon('share')}<strong>Choose a thread for your shared text</strong></div><p class="sharepreview">${esc(sharedText.slice(0,500))}${sharedText.length>500?'…':''}</p><div class="sb-foot"><small>Pocket adds it to the thread draft. Nothing is sent.</small><button data-action="discard-share">Discard</button></div></div>`:''}
function openAppMenu(){
 openSheet(`<div class="sheetinner appmenu"><div class="grabber" aria-hidden="true"></div><header class="appmenuhead"><img src="/logo.svg" alt="BB Pocket" width="168" height="52"><span class="sync ${connectionBad?'offline':''}"><span class="dot"></span>${esc(connection)}</span></header>
 <div class="menugroup"><button class="menuitem" data-action="new-thread">${icon('plus')}<span>New thread</span></button><button class="menuitem" data-action="themes">${icon('projects')}<span>Themes</span></button><button class="menuitem" data-action="share-setup">${icon('share')}<span>Share to Pocket setup</span></button></div>
 <div class="menugroup"><button class="menuitem" data-action="usage">${icon('gauge')}<span>Remaining usage</span></button><button class="menuitem" data-action="menu-refresh">${icon('refresh')}<span>Refresh workspace</span></button><a class="menuitem" href="${bbUrl()}" target="_blank" rel="noopener">${icon('external')}<span>Open full BB</span></a></div>
 <button class="secondary wide" data-action="close">Close</button></div>`,'appmenusheet');$('.brandbutton')?.setAttribute('aria-expanded','true')}
function shareSetup(){
 const steps=['Create a shortcut named <strong>Send to BB Pocket</strong>.','In Details, enable <strong>Show in Share Sheet</strong>. Accept <strong>Text</strong> and <strong>URLs</strong>.','Add <strong>Get Text from Input</strong>, using Shortcut Input.','Add <strong>URL Encode</strong> to encode that text.','Add a <strong>Text</strong> action. Paste the address below, then insert the <strong>URL Encoded Text</strong> variable immediately after the equals sign.','Add <strong>Open URLs</strong>, using the Text action’s output.'];
 openSheet(`<div class="sheetinner">${sheetHead('Share to Pocket',{sub:'Text and links from the iPhone Share Sheet'})}<p class="lead">Use an Apple Shortcut to add “Send to BB Pocket” to the iPhone Share Sheet for text and links.</p><ol class="steps">${steps.map(s=>`<li><span>${s}</span></li>`).join('')}</ol><label class="fieldlabel" for="shareaddress">Your receiving address</label><div class="copyfield"><input id="shareaddress" readonly value="${esc(location.origin+'/#share?text=')}"><button class="primary" data-action="copy-share-address">${icon('copy')}Copy</button></div><div class="howto"><p>Share a link or selected text, choose the shortcut, then choose a thread in Pocket and review before sending.</p><p class="muted">Opens Pocket in your browser; iOS may not open the installed Home Screen app. Sign in to BB Connect if prompted, then share again if necessary. For images, media, PDFs and other files, open a conversation in Pocket and use the attachment button. For long text, paste directly into Pocket.</p></div></div>`)}
function receiveShare(){if(!location.hash.startsWith('#share?'))return;const incoming=new URLSearchParams(location.hash.slice(7)).get('text')||'';if(!incoming.trim()){toast('No shared text received');return}if(incoming.length>20000){toast('Shared text is too long. Paste it into a thread instead.');return}if(sharedText&&sharedText!==incoming){toast('Choose a thread or discard the previous shared text, then share again.');return}if(!save('sharedText',incoming)){toast('Device storage is full; shared text could not be saved');return}sharedText=incoming;history.replaceState({pocket:true},'','#threads')}
async function attachSharedText(id){if(!sharedText)return true;const draft=read('draft:'+id,'');const combined=draft?draft+'\n\n'+sharedText:sharedText;if(combined.length>100000){toast('This draft is too long to add shared text');return false}if(!save('draft:'+id,combined)){toast('Device storage is full; shared text could not be added');return false}sharedText='';save('sharedText','');toast('Shared text added to draft. Review it before you send.');return true}

/* ---------- Home: threads, tasks, projects ---------- */
const tabLabels={threads:'Threads',tasks:'Tasks',projects:'Projects'};
function nav(){return `<nav class="tabbar" aria-label="Main navigation">${['threads','tasks','projects'].map(t=>`<button data-tab="${t}" class="${tab===t?'selected':''}" ${tab===t?'aria-current="page"':''}>${icon(t)}<span>${tabLabels[t]}</span></button>`).join('')}</nav>`}
function banner(){return error?`<div class="notice warn">${icon('alert')}<span>${esc(error)}</span><button data-action="refresh">Retry</button><a href="${bbUrl()}" target="_blank" rel="noopener">BB login</a></div>`:''}
function filterCount(){if(tab==='tasks')return (taskFilters.project?1:0)+(taskFilters.status?1:0);const f=filters;return [f.project,f.status,f.unread==='true',f.sort!=='recent'].filter(Boolean).length+f.include.split(',').filter(Boolean).length+f.exclude.split(',').filter(Boolean).length}
const isDefault=()=>tab==='threads'?JSON.stringify({...filters,q:''})===JSON.stringify({...defaults()}):!taskFilters.project&&!taskFilters.status;
function chip(attrs,label,{kind='',on=false,remove=false,aria=''}={}){return `<button class="chip ${kind} ${on?'on':''}" ${attrs} ${aria?`aria-label="${esc(aria)}"`:''} ${remove||on?'':''}>${label}${remove?`<span class="x" aria-hidden="true">${icon('close',2)}</span>`:''}</button>`}
function chips(){
 if(tab==='projects')return '';
 if(tab==='tasks'){
  const quick=[['todo','To do'],['in_progress','In progress'],['in_review','In review'],['done','Done']];
  return (taskFilters.project?chip(`data-clear="project"`,esc(tname(taskFilters.project)),{remove:true,kind:'scope',aria:'Remove project '+tname(taskFilters.project)}):'')+(taskFilters.status&&!quick.some(([s])=>s===taskFilters.status)?chip(`data-clear="status"`,esc(cap(pretty(taskFilters.status))),{remove:true,on:true}):'')+quick.map(([s,l])=>chip(`data-quick-status="${s}" aria-pressed="${taskFilters.status===s}"`,`<span class="ts s-${s}"></span>${l}`,{on:taskFilters.status===s})).join('');
 }
 const removable=['exclude','include'].map(k=>filters[k].split(',').filter(Boolean).map(l=>chip(`data-rule="${k}" data-label="${esc(l)}"`,`<span class="chipkind">${k==='exclude'?'Hide':'Only'}</span>${esc(lname(l))}`,{kind:k,remove:true,aria:`Remove ${k==='exclude'?'exclude':'include'} ${lname(l)}`})).join('')).join('')
  +(filters.project?chip(`data-clear="project"`,esc(pname(filters.project)),{kind:'scope',remove:true,aria:'Remove project '+pname(filters.project)}):'')
  +(filters.status&&!['running','attention'].includes(filters.status)?chip(`data-clear="status"`,esc(cap(pretty(filters.status))),{on:true,remove:true,aria:'Remove status '+filters.status}):'');
 const quick=chip(`data-quick="unread" aria-pressed="${filters.unread==='true'}"`,'Unread',{on:filters.unread==='true'})+chip(`data-quick="running" aria-pressed="${filters.status==='running'}"`,'<span class="pulse"></span>Running',{on:filters.status==='running'})+chip(`data-quick="attention" aria-pressed="${filters.status==='attention'}"`,'Needs input',{on:filters.status==='attention',kind:'amber'});
 return removable+(removable?'<span class="chipdivider" aria-hidden="true"></span>':'')+quick;
}
function renderChips(){const c=$('#chips');if(c)c.innerHTML=chips();const b=$('.filterbtn .badge');const n=filterCount();if(b){b.textContent=n;b.hidden=!n}}
function renderHome(){
 threadId=null;threadReady=false;document.body.style.overflow='';document.body.dataset.view='home';
 const q=tab==='threads'?filters.q:tab==='tasks'?taskFilters.q:'',n=filterCount();
 app.innerHTML=`<main class="shell home tab-${tab}">
 <header class="topbar"><button class="brandbutton" data-action="app-menu" aria-label="BB Pocket menu" aria-haspopup="dialog" aria-expanded="false"><img class="brandlogo" src="/logo.svg" alt="" width="132" height="41"><img class="brandicon" src="/icon.svg" alt="" width="34" height="34">${icon('down',2)}</button><div id="usagepanel">${usageButton()}</div></header>
 <div class="titlebar"><h1>${tabLabels[tab]}</h1><button class="sync ${connectionBad?'offline':''}" data-action="refresh" aria-label="Refresh"><span class="dot"></span>${esc(connection)}</button></div>
 ${tab==='threads'?shareBanner():''}<div id="banner">${banner()}</div>
 <div class="stickybar"><div class="searchrow"><label class="search">${icon('search')}<input id="search" type="search" enterkeyhint="search" autocomplete="off" placeholder="Search ${tab}${tab==='threads'?' by title, ID or label':''}" aria-label="Search ${tab}" value="${esc(q)}"></label>${tab!=='projects'?`<button class="iconbtn filterbtn" data-action="filters" aria-label="Filters">${icon('filter')}<span class="badge" ${n?'':'hidden'}>${n}</span></button>`:''}</div>${tab==='projects'?'':`<div class="chips" id="chips">${chips()}</div>`}</div>
 <div id="results" aria-live="polite"></div></main>
 ${tab==='threads'?`<button class="fab" data-action="new-thread" aria-label="New thread">${icon('plus',2.2)}<span>New thread</span></button>`:''}
 <div class="ptr" aria-hidden="true">${icon('refresh')}</div>${nav()}`;
 renderResults();
}
function skeleton(){return `<div class="rows">${Array.from({length:7},()=>'<div class="skeleton"><i></i><span><b></b><b></b></span></div>').join('')}</div>`}
function renderResults(){const el=$('#results');if(!el||threadId)return;
 if(tab==='projects'){renderProjects();return}
 if(!data){el.innerHTML=skeleton();return}
 const rows=tab==='threads'?data.threads:data.tasks;
 const sortLabel=tab==='threads'?({oldest:'Oldest first',pinned:'Pinned first'}[filters.sort]||'Recent activity'):'Recently updated';
 el.innerHTML=`<div class="listhead"><span>${data.total.toLocaleString()} ${data.total===1?tab.slice(0,-1):tab}${data.cached?' · saved on device':''}</span>${tab==='threads'?`<button data-action="sort" aria-haspopup="dialog">${esc(sortLabel)}${icon('down',2)}</button>`:`<span>${sortLabel}</span>`}</div><div class="rows">${rows.map(tab==='threads'?threadCard:taskCard).join('')}</div>${rows.length?'':`<div class="empty">${icon(tab==='threads'?'inbox':'tasks')}<p>No ${tab} match these filters.</p>${isDefault()&&!(tab==='threads'?filters.q:taskFilters.q)?'':'<button class="secondary" data-action="reset">Reset filters</button>'}</div>`}${data.nextOffset!==null&&data.nextOffset!==undefined?'<button class="secondary loadmore" data-action="more">Load more</button>':''}`;
}
function hasDraft(id){return !!read('draft:'+id,'')||read('attachments:'+id,[]).length>0}
function threadCard(t){
 const [state,label]=threadState(t);const labels=(t.labels||[]).filter(l=>!filters.exclude.split(',').includes(l)).slice(0,2);
 return `<article class="threadrow" data-thread-card="${esc(t.id)}"><button class="row ${t.unread?'unread':''}" data-thread="${esc(t.id)}"><span class="avatar st-${state}">${providerMark(t.providerId)}${t.unread?'<i class="unreadmark" aria-label="Unread"></i>':''}</span><span class="rowmain"><span class="rowline"><span class="rowtitle">${esc(t.title)}</span><time>${relative(t.updatedAt)}</time></span><span class="rowmeta"><span class="state st-${state}">${label}</span><span class="proj">${esc(pname(t.projectId))}</span>${t.pinnedAt?`<span class="flag" title="Pinned">${icon('pin')}</span>`:''}${hasDraft(t.id)?`<span class="draftmark">${icon('draft')}Draft</span>`:''}${labels.map(l=>`<span class="tag">${esc(lname(l))}</span>`).join('')}</span></span></button><button class="rowmenu" data-thread-menu="${esc(t.id)}" aria-label="Thread actions for ${esc(t.title)}" aria-haspopup="dialog">${icon('more')}</button></article>`;
}
function taskCard(t){return `<button class="row taskrow" data-task="${esc(t.id)}"><span class="ts s-${esc(t.status)}" title="${esc(pretty(t.status))}"></span><span class="rowmain"><span class="rowline"><span class="rowtitle">${esc(t.title)}</span><time>${relative(t.updatedAt)}</time></span><span class="rowmeta"><span class="key">${esc(t.key)}</span><span class="state">${esc(cap(pretty(t.status)))}</span>${t.priority&&t.priority!=='none'?`<span class="prio p-${esc(t.priority)}">${esc(cap(t.priority))}</span>`:''}${t.dueDate?`<span class="due">Due ${esc(t.dueDate)}</span>`:''}<span class="proj">${esc(tname(t.projectId))}</span></span></span></button>`}
function renderProjects(){
 const query=($('#search')?.value||'').toLowerCase();const match=p=>p.name.toLowerCase().includes(query)||(p.prefix||'').toLowerCase().includes(query);
 const section=(title,ps,task)=>{const shown=ps.filter(match);return `<section class="projectsection"><h2 class="sectionlabel">${title}<span>${shown.length}</span></h2>${shown.length?`<div class="projectgrid">${shown.map(p=>{const label=meta.labels.find(l=>l.name===p.name)?.slug||'';return `<article class="projectcard ${task?'':'compact'}"><div class="pc-head"><span class="monogram ${task?'':'bb'}">${esc((p.prefix||p.name.slice(0,2)).toUpperCase())}</span><h3>${esc(p.name)}</h3></div><div class="actions">${task?`<button data-project-tasks="${esc(p.id)}">${icon('tasks')}Tasks</button>`:''}${!task||p.linkedBbProjectId?`<button data-project-threads="${esc(task?p.linkedBbProjectId:p.id)}" ${task?`data-project-label="${esc(label)}"`:''}>${icon('threads')}Threads</button>`:''}</div></article>`}).join('')}</div>`:'<p class="muted pad">No matches.</p>'}</section>`};
 $('#results').innerHTML=section('Task projects',meta.taskProjects,true)+section('BB projects',meta.projects,false);
}
function listKey(){return tab+'?'+new URLSearchParams(tab==='threads'?filters:taskFilters)}
async function loadHome({more=false}={}){
 if(threadId||tab==='projects')return;const requestEpoch=++epoch,key=listKey(),currentTab=tab;
 if(!more&&!data){const c=await get(key);if(epoch!==requestEpoch)return;if(c){data={...c,cached:true};renderResults();syncText('Saved · refreshing')}}
 try{const result=await api(key+(more?'&offset='+data.nextOffset:'&limit='+Math.max(60,data?.[currentTab]?.length||60)));if(epoch!==requestEpoch||threadId||tab!==currentTab)return;error='';data=more?{...result,[currentTab]:[...data[currentTab],...result[currentTab]]}:result;renderResults();error=result.warning?'BB is unavailable. Showing saved data.':'';$('#banner')&&($('#banner').innerHTML=banner());syncText(result.warning?'BB unavailable':result.stale?'Refreshing':'Up to date',!!result.warning);put(key,data)}catch(e){if(epoch!==requestEpoch)return;error=e.message;$('#banner')&&($('#banner').innerHTML=banner());syncText(navigator.onLine?'Reconnecting':'Offline · saved',true);if(!data&&$('#results')){$('#results').innerHTML=`<div class="empty">${icon('alert')}<p>Couldn’t load your workspace.<br>Your filters and drafts are safe.</p><button class="secondary" data-action="refresh">Try again</button></div>`}}
}
function changed(){save('filters',filters);save('taskFilters',taskFilters);data=null;renderChips();renderResults();loadHome()}
function setTab(t){epoch++;tab=t;save('tab',tab);data=null;history.pushState({pocket:true},'','#'+t);route=t;renderHome();loadHome();window.scrollTo(0,0)}

/* ---------- Filters ---------- */
function seg(name,items,current,{wrap=false}={}){return `<div class="seg ${wrap?'wrap':''}" role="radiogroup">${items.map(([v,l])=>`<label class="segopt"><input type="radio" name="${esc(name)}" value="${esc(v)}" ${current===v?'checked':''}><span>${l}</span></label>`).join('')}</div>`}
function option(value,label,current){return `<option value="${esc(value)}" ${current===value?'selected':''}>${esc(label)}</option>`}
function pickRow(id,name,label,options,current,currentLabel){return `<div class="pickrow"><span class="pk">${esc(label)}</span><span class="pv">${esc(currentLabel)}</span>${icon('chevron',2)}<select id="${id}" name="${name}" aria-label="${esc(label)}">${options}</select></div>`}
function openFilters(){
 const thread=tab==='threads',f=thread?filters:taskFilters;
 const projects=thread?meta.projects:meta.taskProjects,currentProject=projects.find(p=>p.id===f.project)?.name||'All projects';
 const ruleOf=slug=>f.exclude?.split(',').includes(slug)?'exclude':f.include?.split(',').includes(slug)?'include':'';
 const statuses=thread?[['','Any'],['running','Running'],['attention','Needs input'],['idle','Idle'],['error','Error'],['pending','Pending']]:[['','Any'],['backlog','Backlog'],['todo','To do'],['in_progress','In progress'],['in_review','In review'],['done','Done'],['canceled','Canceled']];
 openSheet(`<form id="filterform" class="sheetinner filtersheet">${sheetHead(thread?'Filter threads':'Filter tasks',{left:`<button type="button" class="textbtn" data-action="reset">Reset</button>`})}
 <div class="sheetbody">
 ${thread&&views.length?`<div class="fgroup"><p class="fl">Saved views</p><div class="viewchips">${views.map((v,i)=>`<span class="viewchip"><button type="button" data-view="${i}">${esc(v.name)}</button><button type="button" data-delete-view="${i}" aria-label="Delete ${esc(v.name)}">${icon('close',2)}</button></span>`).join('')}</div></div>`:''}
 ${thread?`<div class="fgroup"><p class="fl">Show</p>${seg('unread',[['false','All threads'],['true','Unread only']],f.unread)}</div>`:''}
 <div class="fgroup"><p class="fl" id="statuslabel">Status</p>${seg('status',statuses,f.status||'',{wrap:true})}</div>
 <div class="fgroup">${pickRow('projectfilter','project','Project',option('','All projects',f.project)+projects.map(p=>option(p.id,p.name,f.project)).join(''),f.project,currentProject)}</div>
 ${thread?`<div class="fgroup"><p class="fl">Sort</p>${seg('sort',[['recent','Recent'],['oldest','Oldest'],['pinned','Pinned first']],f.sort)}</div>
 <div class="fgroup"><p class="fl">Labels <span>Combine Only and Hide rules</span></p>${meta.labels.length?`<div class="labelrules">${meta.labels.map(l=>`<div class="labelrule"><span>${esc(l.name)}</span>${seg('label:'+l.slug,[['','Any'],['include','Only'],['exclude','Hide']],ruleOf(l.slug))}</div>`).join('')}</div>`:'<p class="muted">No labels yet.</p>'}</div>
 <div class="fgroup"><p class="fl">Save as view</p><div class="copyfield"><input id="viewname" placeholder="e.g. Running work" aria-label="Save current filters as a view"><button type="button" class="secondary" data-action="saveview">Save</button></div></div>`:''}
 </div><footer class="sheetfoot"><button class="primary wide" type="submit">Apply filters</button></footer></form>`,'tallsheet');
}
function applyForm(){const f=Object.fromEntries(new FormData($('#filterform')));if(tab==='threads'){const include=[],exclude=[];for(const [k,v]of Object.entries(f))if(k.startsWith('label:')&&v)(v==='include'?include:exclude).push(k.slice(6));filters={...filters,project:f.project||'',status:f.status||'',unread:f.unread||'false',sort:f.sort||'recent',include:include.join(','),exclude:exclude.join(',')}}else taskFilters={...taskFilters,project:f.project||'',status:f.status||''}}
function openSort(){const opts=[['recent','Recent activity'],['oldest','Oldest first'],['pinned','Pinned first']];openSheet(`<div class="sheetinner">${sheetHead('Sort threads')}<div class="menugroup">${opts.map(([v,l])=>`<button class="menuitem ${filters.sort===v?'checked':''}" data-sort="${v}"><span>${l}</span>${filters.sort===v?icon('check',2):''}</button>`).join('')}</div></div>`)}

/* ---------- Thread menu ---------- */
function menuShell(title,content,sub=''){openSheet(`<div class="sheetinner threadmenusheet">${sheetHead(title,{sub})}${content}</div>`)}
const actionIcons={split:'split','copy-id':'copy','copy-local':'link','copy-cloud':'link',read:'eye',unread:'dot',pin:'pin',unpin:'pin',rename:'edit',archive:'archive',unarchive:'archive',delete:'trash','confirm-delete':'trash','cancel-delete':'back',retry:'refresh'};
function menuButton(action,label,extra=''){return `<button class="menuitem ${['delete','confirm-delete'].includes(action)?'destructive':''}" data-thread-action="${action}" ${extra}>${icon(actionIcons[action]||'dot')}<span>${label}</span></button>`}
function renderThreadMenu(){if(!menuInfo)return;const t=menuInfo.thread;const [,label]=threadState(t);menuShell(t.title,`<div class="menugroup">${menuButton(t.unread?'read':'unread',t.unread?'Mark read':'Mark unread')}${menuButton(t.pinnedAt?'unpin':'pin',t.pinnedAt?'Unpin':'Pin')}${menuButton('rename','Rename')}</div><div class="menugroup">${menuButton('split','Open in split <small>In connected full BB</small>')}${menuButton('copy-id','Copy thread ID')}${menuButton('copy-local','Copy local link')}${menuButton('copy-cloud','Copy cloud link',menuInfo.cloudLink?'':'disabled')}</div><div class="menugroup">${menuButton(t.archivedAt?'unarchive':'archive',t.archivedAt?'Unarchive':'Archive')}${menuButton('delete','Delete')}</div>${threadId===menuThread?`<div class="menugroup"><button class="menuitem destructive" data-action="stop">${icon('stop')}<span>Stop agent</span></button></div>`:''}`,`${esc(pname(t.projectId))} · ${esc(label)}`)}
async function openThreadMenu(id){if(menuBusy)return;menuThread=id;menuInfo=null;const token=++menuEpoch;menuShell('Thread actions','<div class="menugroup loadingmenu"><div class="skeletonline"></div><div class="skeletonline"></div><div class="skeletonline"></div></div>');try{const info=await api(`thread/${id}/menu`);if(token!==menuEpoch||!sheet.open)return;menuInfo=info;renderThreadMenu()}catch(e){if(token===menuEpoch&&sheet.open)menuShell('Thread actions',`<p class="notice warn">${esc(e.message)}</p><div class="menugroup">${menuButton('retry','Retry')}</div>`)}}
async function copyMenuText(value){try{await navigator.clipboard.writeText(value);sheet.close();toast('Copied')}catch{menuShell('Copy',`<p>Select and copy:</p><textarea readonly id="copyvalue">${esc(value)}</textarea>`);$('#copyvalue').select()}}
async function threadAction(action){if(menuBusy||!menuThread)return;const id=menuThread;
 if(action==='retry')return openThreadMenu(id);
 if(action.startsWith('copy-')){if(!menuInfo)return;return copyMenuText(action==='copy-id'?id:action==='copy-local'?menuInfo.localLink:menuInfo.cloudLink)}
 if(action==='rename'){menuShell('Rename thread',`<form id="rename-thread" class="stack"><label class="fieldlabel" for="thread-name">Title</label><input id="thread-name" required maxlength="500" value="${esc(menuInfo.thread.title)}" enterkeyhint="done"><button class="primary wide" type="submit">Save name</button></form>`);$('#thread-name').focus();$('#thread-name').select();return}
 let input={action};if(action==='save-rename'){input={action:'rename',title:$('#thread-name').value.trim()};if(!input.title)return}
 if(action==='delete'){menuBusy=true;try{const d=await api(`thread/${id}/action`,{action:'children'});if(!sheet.open||menuThread!==id)return;const count=d.result.nonDeletedChildCount;menuShell('Delete thread?',`<p class="lead">Delete “${esc(menuInfo.thread.title)}”? You cannot undo this.</p>${count?`<p class="notice warn">${icon('alert')}<span>This thread has ${count} child thread${count===1?'':'s'}.</span></p><label class="checkrow"><input type="checkbox" id="confirm-children"> I understand this thread has child threads.</label>`:''}<div class="menugroup">${menuButton('confirm-delete','Delete thread')}${menuButton('cancel-delete','Cancel')}</div>`)}catch(e){toast(e.message)}finally{menuBusy=false}return}
 if(action==='cancel-delete'){renderThreadMenu();return}
 if(action==='confirm-delete'){const c=$('#confirm-children');if(c&&!c.checked){toast('Confirm the child-thread warning first');c.closest('label')?.classList.add('shake');return}input={action:'delete',confirmed:true,childThreadsConfirmed:!!c?.checked}}
 menuBusy=true;for(const b of sheet.querySelectorAll('button,input'))b.disabled=true;
 try{const d=await api(`thread/${id}/action`,input);sheet.close();if(input.action==='split'){toast(d.result?.delivered?'Split request sent to connected BB':'No connected full BB window received the split request');return}
  toast(input.action==='delete'?'Thread deleted':input.action==='rename'?'Thread renamed':{pin:'Pinned',unpin:'Unpinned',read:'Marked read',unread:'Marked unread',archive:'Archived',unarchive:'Unarchived'}[input.action]||'Thread updated');
  if(threadId===id&&['delete','archive'].includes(input.action)){navigate(tab)}else if(threadId===id){refreshThread()}else{data=null;loadHome()}
 }catch(e){toast(e.message);for(const b of sheet.querySelectorAll('button,input'))b.disabled=false}finally{menuBusy=false}
}
sheet.addEventListener('close',()=>{menuEpoch++;$('.brandbutton')?.setAttribute('aria-expanded','false')});

// Long press (550 ms) or right-click opens the thread menu. Movement or scrolling cancels it.
let press=null,suppressClickUntil=0;
function cancelPress(){if(press){clearTimeout(press.timer);press.row?.classList.remove('pressing')}press=null}
document.addEventListener('pointerdown',e=>{if(e.button!==0||!e.isPrimary)return;const row=e.target.closest('[data-thread-card]');if(!row||e.target.closest('[data-thread-menu]'))return;cancelPress();row.classList.add('pressing');press={id:row.dataset.threadCard,row,x:e.clientX,y:e.clientY,timer:setTimeout(()=>{const id=press?.id;cancelPress();if(id){suppressClickUntil=Date.now()+1000;navigator.vibrate?.(8);openThreadMenu(id)}},550)}});
document.addEventListener('pointermove',e=>{if(press&&Math.hypot(e.clientX-press.x,e.clientY-press.y)>10)cancelPress()},{passive:true});
for(const event of ['pointerup','pointercancel','scroll'])document.addEventListener(event,cancelPress,{capture:true,passive:true});
document.addEventListener('contextmenu',e=>{const row=e.target.closest('[data-thread-card]');if(row){e.preventDefault();cancelPress();suppressClickUntil=Date.now()+1000;openThreadMenu(row.dataset.threadCard)}});
document.addEventListener('click',e=>{if(Date.now()<suppressClickUntil&&e.target.closest('[data-thread-card]')){e.preventDefault();e.stopImmediatePropagation()}},true);

/* ---------- Attachments ---------- */
function draftFiles(id=threadId){return read('attachments:'+id,[])}
const fileSize=b=>b>=1048576?(b/1048576).toFixed(1)+' MB':Math.max(1,Math.round(b/1024))+' KB';
function renderDraftFiles(){const el=$('#draftfiles');if(!el)return;const files=draftFiles();el.innerHTML=files.map(f=>`<div class="draftfile">${icon('file')}<span class="df-name">${esc(f.name)}<small>${fileSize(f.sizeBytes)}</small></span><button type="button" data-remove-attachment="${esc(f.id)}" aria-label="Remove ${esc(f.name)}">${icon('close',2)}</button></div>`).join('');el.hidden=!files.length;updateSendState()}
function uploadFile(id,file,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`/api/thread/${id}/attachments`);xhr.setRequestHeader('x-pocket-request','1');xhr.setRequestHeader('x-pocket-filename',encodeURIComponent(file.name));xhr.setRequestHeader('content-type',file.type||'application/octet-stream');xhr.timeout=180000;xhr.upload.onprogress=e=>onProgress(e.lengthComputable?Math.round(e.loaded/e.total*100):0);xhr.onerror=xhr.ontimeout=()=>reject(new Error('Upload interrupted. Please select the file again.'));xhr.onload=()=>{try{const d=JSON.parse(xhr.responseText);if(xhr.status<200||xhr.status>=300)throw Error(d.error||'Upload failed');resolve(d)}catch(e){reject(new Error(e.message||'Sign in to BB Connect and retry'))}};xhr.send(file)})}
function uploadStatus(text,percent){const el=$('#uploadstatus');if(!el)return;el.hidden=!text;el.innerHTML=text?`<span>${esc(text)}</span><div class="meter"><i style="width:${percent||0}%"></i></div>`:''}
async function addFiles(files){const id=threadId;if(!id||attachmentUpload)return;if(!navigator.onLine){toast('Connect before adding attachments');return}if(draftFiles(id).length+files.length>20){toast('Maximum 20 attachments per message');return}if(draftFiles(id).reduce((n,f)=>n+f.sizeBytes,0)+files.reduce((n,f)=>n+f.size,0)>100*1024*1024){toast('Maximum total attachment size is 100 MB');return}if(files.some(f=>f.size>50*1024*1024)){toast('Maximum file size is 50 MB');return}attachmentUpload=true;
 try{for(const file of files){uploadStatus(`Uploading ${file.name} · 0%`,0);const d=await uploadFile(id,file,percent=>{if(threadId===id)uploadStatus(`Uploading ${file.name} · ${percent}%`,percent)});const next=[...draftFiles(id),d];if(!save('attachments:'+id,next))throw Error('Device storage is full; attachment draft could not be saved');if(threadId===id)renderDraftFiles()}}catch(e){toast(e.message)}finally{attachmentUpload=false;if(threadId===id)uploadStatus('');if($('#attachfiles'))$('#attachfiles').value=''}
}
document.addEventListener('change',e=>{if(e.target.id==='attachfiles')addFiles([...e.target.files]);const pick=e.target.closest?.('.pickrow');if(pick&&e.target.tagName==='SELECT'){const pv=pick.querySelector('.pv');if(pv)pv.textContent=e.target.selectedOptions[0]?.textContent||''}});
document.addEventListener('paste',e=>{if(e.target.id!=='draft')return;const files=[...e.clipboardData.files];if(files.length){e.preventDefault();addFiles(files)}else{const html=e.clipboardData.getData('text/html');if(html)addFiles([new File([html],'pasted-rich-text.html',{type:'text/html'})])}});

/* ---------- Conversation ---------- */
function updateSendState(){const b=$('#compose .sendbtn'),d=$('#draft');if(b&&d)b.classList.toggle('ready',!!d.value.trim()||draftFiles().length>0)}
function autosize(el){el.style.height='auto';el.style.height=Math.min(el.scrollHeight,168)+'px'}
function threadShell(id){
 document.body.style.overflow='hidden';document.body.dataset.view='thread';
 const cached=data?.threads?.find(t=>t.id===id);
 app.innerHTML=`<section class="threadview enter"><header class="threadhead"><button class="iconbtn ghost" data-action="back" aria-label="Back">${icon('back',2.2)}</button><div class="title"><h2 id="threadtitle">${esc(cached?.title||'Conversation')}</h2><small id="threadsubtitle">${cached?esc(pname(cached.projectId)):'Loading conversation…'}</small></div><button class="iconbtn ghost" data-action="threadmenu" aria-label="Thread actions">${icon('more')}</button></header><div id="threadstrip"></div><div class="messages" id="messages"><div class="convloading"><div class="bubble-skel"></div><div class="bubble-skel me"></div><div class="bubble-skel"></div></div></div><div class="composer"><button class="jump" data-action="jump" aria-label="Jump to latest" hidden>${icon('arrowdown',2)}</button><div id="draftfiles" hidden></div><div id="uploadstatus" role="status" hidden></div><form id="compose"><label class="attachbutton" title="Attach images, media, PDFs or files">${icon('clip')}<input id="attachfiles" type="file" multiple aria-label="Attach files"></label><textarea id="draft" aria-label="Message" placeholder="Message ${esc(cached?providerName(cached.providerId):'your agent')}…" rows="1" enterkeyhint="enter"></textarea><button type="submit" class="sendbtn" aria-label="Send message">${icon('send',2.4)}</button></form></div></section>`;
 const draft=$('#draft');draft.value=read('draft:'+id,'');renderDraftFiles();requestAnimationFrame(()=>autosize(draft));updateSendState();
 const m=$('#messages');m.addEventListener('scroll',()=>{const fromBottom=m.scrollHeight-m.clientHeight-m.scrollTop;save('scroll:'+id,{top:m.scrollTop,bottom:fromBottom<100});$('.jump').hidden=fromBottom<320},{passive:true});
}
async function openThread(id){epoch++;threadId=id;threadData=null;olderRows=[];olderCursor=null;threadReady=false;renderedRows='';threadShell(id);const c=await get('thread:'+id);if(threadId!==id)return;if(c){threadData=c;renderThread(true);syncText('Saved · refreshing')}await refreshThread(true);if(pending[id]&&threadId===id)checkDelivery()}
const timeOf=t=>new Date(t).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'});
function dayLabel(t){const d=new Date(t),today=new Date();const diff=Math.round((new Date(today.toDateString())-new Date(d.toDateString()))/86400000);return diff===0?'Today':diff===1?'Yesterday':d.toLocaleDateString(undefined,{weekday:diff<7?'long':undefined,month:'short',day:'numeric'})}
function rowHtml(r,provider){
 if(r.kind==='conversation'){const user=r.role==='user';return `<article class="message ${user?'user':'assistant'}" id="row-${esc(r.id)}">${user?'':`<header><span class="who">${providerMark(provider)}${esc(providerName(provider))}</span><time>${timeOf(r.createdAt)}</time></header>`}<div class="prose">${md(r.text)}</div>${r.attachments&&(r.attachments.localImages||r.attachments.localFiles||r.attachments.webImages)?`<p class="attachnote">${icon('clip')}Attachments available in BB</p>`:''}${user?`<time class="mtime">${timeOf(r.createdAt)}</time>`:''}</article>`}
 if(r.kind==='turn')return `<details class="activity"><summary>${icon('tool')}<span>${r.status==='completed'?'Turn completed':'Agent '+esc(r.status)} · ${r.summaryCount||0} activity items</span>${icon('chevron',2)}</summary><p class="muted">Open BB for the full tool transcript.</p></details>`;
 if(r.kind==='system')return `<details class="activity system"><summary>${icon('alert')}<span>${esc(r.title||r.systemKind||'Status')}</span>${icon('chevron',2)}</summary><pre>${esc(r.detail||'')}</pre></details>`;
 return `<details class="activity"><summary>${icon('tool')}<span>${esc(r.title||r.label||r.kind||'Agent activity')}</span>${icon('chevron',2)}</summary><pre>${esc(r.text||r.detail||r.status||'')}</pre></details>`;
}
function timelineHtml(rows,provider){let html='',group=[],lastDay='';const flush=()=>{if(!group.length)return;const working=group.some(r=>r.status==='pending');html+=`<details class="activity ${working?'working':''}"><summary>${icon('tool')}<span>${group.length} agent ${group.length===1?'activity':'activities'} · ${working?'working':'completed'}</span>${icon('chevron',2)}</summary><div class="steps-list">${group.map(r=>`<details class="step"><summary>${esc(r.command?.split('\n')[0]?.slice(0,100)||r.title||r.workKind||r.kind)}</summary><pre>${esc(r.output||r.text||r.detail||r.status||'')}</pre></details>`).join('')}</div></details>`;group=[]};
 for(const r of rows){if(r.kind==='work'||r.kind==='thinking')group.push(r);else{flush();if(r.kind==='conversation'&&r.createdAt){const day=new Date(r.createdAt).toDateString();if(day!==lastDay){lastDay=day;html+=`<div class="daysep"><span>${esc(dayLabel(r.createdAt))}</span></div>`}}html+=rowHtml(r,provider)}}flush();return html}
function deliveryHtml(){const p=pending[threadId];if(!p)return '';const state=p.state==='sent'?'sent':p.state==='sending'?'sending':p.state==='missing'?'missing':'unknown';const label={sent:'Sent to BB',sending:'Sending…',missing:'Not submitted. Your draft is saved.',unknown:'Delivery unconfirmed. Check the conversation before you send again.'}[state];return `<div class="delivery d-${state}"><p class="d-text">${esc(p.text.slice(0,160))}${p.attachmentNames?.length?' · '+esc(p.attachmentNames.join(', ')):''}</p><p class="d-state">${state==='sent'?icon('check',2):state==='sending'?'<span class="spinner"></span>':icon('alert')}${label}</p>${p.state!=='sending'?'<div class="d-actions"><button data-action="delivery">Check delivery</button><button data-action="dismissdelivery">Dismiss</button></div>':''}</div>`}
function renderStrip(){const el=$('#threadstrip');if(!el)return;const t=threadData?.thread;let html='';
 if(connectionBad)html+=`<div class="strip offline">${icon('alert')}<span>${esc(connection)}</span><button data-action="refresh">Retry</button></div>`;
 if(t&&t.hasPendingInteraction)html+=`<div class="strip attention">${icon('alert')}<span>Your agent needs input.</span><a href="${bbUrl()}" target="_blank" rel="noopener">Open BB</a></div>`;
 else if(t&&running(liveStatus(t)))html+=`<div class="strip working"><span class="pulse"></span><span>${liveStatus(t)==='stopping'?'Stopping…':'Agent is working…'}</span>${liveStatus(t)!=='stopping'?`<button data-action="stop">${icon('stop',2)}Stop</button>`:''}</div>`;
 if(el.innerHTML!==html)el.innerHTML=html}
function renderThread(initial=false){if(!threadData||!threadId)return;const t=threadData.thread;const [state,label]=threadState({...t,status:liveStatus(t)});
 $('#threadtitle').textContent=t.title||t.titleFallback||'Conversation';$('#threadsubtitle').innerHTML=`<span class="statusdot st-${state}"></span>${esc(label)} · ${esc(pname(t.projectId))} · ${esc(providerName(t.providerId))}`;
 const d=$('#draft');if(d&&!d.value)d.placeholder=`Message ${providerName(t.providerId)}…`;renderStrip();
 const rows=[...new Map([...olderRows,...threadData.rows].map(r=>[r.id,r])).values()].sort((a,b)=>a.sourceSeqStart-b.sourceSeqStart);
 const html=`${olderCursor||threadData.timelinePage?.hasOlderRows?'<button class="secondary loadmore" data-action="older">Load earlier messages</button>':''}${rows.length?'':'<div class="empty small">'+icon('threads')+'<p>No messages yet.</p></div>'}${timelineHtml(rows,t.providerId)}${running(liveStatus(t))?'<div class="typing" aria-label="Agent is working"><i></i><i></i><i></i></div>':''}${deliveryHtml()}`;
 if(html===renderedRows)return;renderedRows=html;const m=$('#messages'),oldTop=m.scrollTop,oldHeight=m.scrollHeight,atBottom=oldHeight-m.clientHeight-oldTop<100,opened=[...m.querySelectorAll('details[open]')].map(e=>e.querySelector('summary')?.textContent);m.innerHTML=html;for(const el of m.querySelectorAll('details'))if(opened.includes(el.querySelector('summary')?.textContent))el.open=true;
 if(initial&&!threadReady){const pos=read('scroll:'+threadId,null);m.scrollTop=pos&&!pos.bottom?pos.top:m.scrollHeight;threadReady=true}else if(loadingOlder)m.scrollTop=oldTop+(m.scrollHeight-oldHeight);else m.scrollTop=atBottom?m.scrollHeight:oldTop;
}
async function refreshThread(initial=false){const id=threadId;if(!id)return;try{const d=await api(`thread/${id}/timeline`);if(threadId!==id)return;threadData=d;error='';syncText('Connected');renderThread(initial);put('thread:'+id,d)}catch(e){if(threadId!==id)return;syncText(navigator.onLine?'Reconnecting':'Offline · saved',true);if(!threadData)$('#messages').innerHTML=`<div class="empty">${icon('alert')}<p>${esc(e.message)}</p><button class="secondary" data-action="refresh">Retry</button></div>`}}
async function older(){if(loadingOlder)return;loadingOlder=true;const id=threadId;try{const cursor=olderCursor||threadData.timelinePage?.olderCursor;if(!cursor)return;const d=await api(`thread/${id}/timeline?`+new URLSearchParams({beforeAnchorSeq:cursor.anchorSeq,beforeAnchorId:cursor.anchorId}));if(threadId!==id)return;olderRows=[...d.rows,...olderRows];olderCursor=d.timelinePage?.olderCursor||null;if(!d.timelinePage?.hasOlderRows)threadData.timelinePage.hasOlderRows=false;renderThread()}catch(e){toast(e.message)}finally{loadingOlder=false}}
async function sendMessage(){const id=threadId,text=$('#draft').value.trim(),attachments=draftFiles(id);if(attachmentUpload){toast('Wait for uploads to finish');return}if(!text&&!attachments.length)return;if(!navigator.onLine){toast('Offline. Your draft is saved.');return}if(pending[id]&&pending[id].state!=='sent'){toast('Check the previous message’s delivery first.');return}const record={id:crypto.randomUUID(),text,attachmentIds:attachments.map(f=>f.id),attachmentNames:attachments.map(f=>f.name),state:'sending'};pending[id]=record;save('pending',pending);$('#compose .sendbtn').disabled=true;renderThread();const m=$('#messages');m.scrollTop=m.scrollHeight;try{const result=await api(`thread/${id}/send`,record);record.state=result.state;if(result.state==='sent'){save('attachments:'+id,[]);if(threadId===id)renderDraftFiles();save('draft:'+id,'');if(threadId===id){$('#draft').value='';autosize($('#draft'));updateSendState()}toast('Message sent')}else toast('Delivery unconfirmed. Check the conversation.')}catch{record.state='unknown';toast('Connection interrupted. Checking delivery is safe.')}finally{pending[id]=record;save('pending',pending);if(threadId===id){$('#compose .sendbtn').disabled=false;await refreshThread();}}}
async function checkDelivery(){const id=threadId,p=pending[id];if(!p)return;try{const d=await api(`thread/${id}/delivery?id=${p.id}`);p.state=d.state;save('pending',pending);if(d.state==='sent'){save('attachments:'+id,[]);if(threadId===id)renderDraftFiles();save('draft:'+id,'');if(threadId===id){$('#draft').value='';updateSendState()}toast('BB received your message')}else toast(d.state==='missing'?'Message was not submitted. You can dismiss and send your draft.':'Delivery still unconfirmed. Check the conversation.');if(threadId===id)renderThread()}catch(e){toast(e.message)}}

/* ---------- Task detail ---------- */
async function openTask(id){epoch++;threadId=null;document.body.style.overflow='';document.body.dataset.view='task';app.innerHTML=`<main class="taskdetail enter"><header class="detailhead"><button class="iconbtn ghost" data-action="back" aria-label="Back">${icon('back',2.2)}</button><span class="detailkicker">Task</span></header><div id="taskcontent"><div class="convloading"><div class="skeletonline wide"></div><div class="skeletonline"></div><div class="skeletonline"></div></div></div></main>`;window.scrollTo(0,0);const path='task/'+id,c=await get(path);if(route!==path)return;if(c)renderTask(c);try{const d=await api(path);if(route!==path)return;renderTask(d);put(path,d)}catch(e){toast(e.message)}}
function renderTask(d){if(!d.task){$('#taskcontent').innerHTML='<div class="empty">Task not found</div>';return}const t=d.task;$('.detailkicker').textContent=`${t.key} · ${tname(t.projectId)}`;
 $('#taskcontent').innerHTML=`<h1>${esc(t.title)}</h1><div class="taskmeta"><span class="pill"><span class="ts s-${esc(t.status)}"></span>${esc(cap(pretty(t.status)))}</span>${t.priority&&t.priority!=='none'?`<span class="pill prio p-${esc(t.priority)}">${esc(cap(t.priority))} priority</span>`:''}${t.dueDate?`<span class="pill">Due ${esc(t.dueDate)}</span>`:''}<span class="pill key">${esc(t.key)}</span></div>${t.description?`<div class="prose card">${md(t.description)}</div>`:'<p class="muted">No description.</p>'}<h2 class="sectionlabel">Linked threads<span>${(d.taskThreads||[]).length}</span></h2>${(d.taskThreads||[]).map(x=>`<button class="linkrow" data-thread="${esc(x.threadId)}">${icon('threads')}<span><b>${esc(x.title||x.threadId)}</b><small>${esc(cap(pretty(x.status)))}</small></span>${icon('chevron',2)}</button>`).join('')||'<p class="muted">No linked threads</p>'}<h2 class="sectionlabel">Comments<span>${d.comments.length}</span></h2>${d.comments.map(c=>`<article class="comment"><header><span class="initial">${esc((c.authorName||'?').slice(0,1).toUpperCase())}</span><b>${esc(c.authorName)}</b><time>${relative(c.createdAt)}</time></header><div class="prose">${md(c.body)}</div></article>`).join('')||'<p class="muted">No comments</p>'}`}

/* ---------- Routing and events ---------- */
function navigate(hash){history.pushState({pocket:true},'','#'+hash);handleRoute()}
function handleRoute(){receiveShare();epoch++;route=location.hash.slice(1)||tab;if(route.startsWith('thread/')){openThread(route.slice(7));return}if(route.startsWith('task/')){openTask(route.slice(5));return}tab=['threads','tasks','projects'].includes(route)?route:'threads';threadId=null;data=null;renderHome();loadHome();requestAnimationFrame(()=>window.scrollTo(0,listScroll))}
function goBack(){if(history.state?.pocket)history.back();else navigate(tab)}
async function refresh(){refreshUsage(true);if(threadId)return refreshThread();if(route.startsWith('task/'))return openTask(route.slice(5));await refreshMeta();await loadHome()}
async function refreshMeta(){try{const d=await api('meta');meta=d;await put('meta',d);if(!threadId&&!route.startsWith('task/')){if(tab==='projects')renderProjects();else{renderResults();renderChips()}}}catch(e){syncText('Reconnecting',true)}}

document.addEventListener('input',e=>{if(e.target.id==='search'){if(tab==='projects'){renderProjects();return}const f=tab==='threads'?filters:taskFilters;f.q=e.target.value;save(tab==='threads'?'filters':'taskFilters',f);clearTimeout(searchTimer);searchTimer=setTimeout(()=>{data=null;loadHome()},200)}if(e.target.id==='draft'){if(!save('draft:'+threadId,e.target.value))toast('Device storage is full; draft cannot be saved');autosize(e.target);updateSendState()}});
document.addEventListener('keydown',e=>{if(e.target.id==='search'&&e.key==='Enter')e.target.blur()});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='filterform'){applyForm();sheet.close();changed()}if(e.target.id==='compose')sendMessage();if(e.target.id==='rename-thread')threadAction('save-rename')});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.removeAttachment){save('attachments:'+threadId,draftFiles().filter(f=>f.id!==d.removeAttachment));renderDraftFiles();return}if(d.threadMenu){openThreadMenu(d.threadMenu);return}if(d.threadAction){threadAction(d.threadAction);return}
 if(d.tab){if(d.tab===tab&&!threadId){window.scrollTo({top:0,behavior:'smooth'});return}listScroll=0;setTab(d.tab)}
 if(d.thread){if(!await attachSharedText(d.thread))return;listScroll=window.scrollY;navigate('thread/'+d.thread)}if(d.task){listScroll=window.scrollY;navigate('task/'+d.task)}
 if(d.rule){filters[d.rule]=filters[d.rule].split(',').filter(l=>l!==d.label).join(',');changed()}
 if(d.clear){(tab==='threads'?filters:taskFilters)[d.clear]=d.clear==='unread'?'false':'';changed()}
 if(d.quick){if(d.quick==='unread')filters.unread=filters.unread==='true'?'false':'true';else filters.status=filters.status===d.quick?'':d.quick;changed()}
 if(d.quickStatus){taskFilters.status=taskFilters.status===d.quickStatus?'':d.quickStatus;changed()}
 if(d.sort){filters.sort=d.sort;sheet.close();changed()}
 if(d.projectTasks){taskFilters.project=d.projectTasks;save('taskFilters',taskFilters);setTab('tasks')}
 if(d.projectThreads){filters.project=d.projectThreads;if(d.projectLabel!==undefined)filters.include=d.projectLabel;save('filters',filters);setTab('threads')}
 if(d.view!==undefined){filters={...views[Number(d.view)].filters};sheet.close();renderHome();changed();toast('View applied')}
 if(d.deleteView!==undefined){views.splice(Number(d.deleteView),1);save('views',views);sheet.close();openFilters()}
 const action=d.action;if(action==='new-thread')openNewThread();if(action==='app-menu')openAppMenu();if(action==='themes')openThemeMenu(menuShell,toast);if(action==='menu-refresh'){sheet.close();refresh();toast('Refreshing workspace')}if(action==='share-setup')shareSetup();if(action==='discard-share'){sharedText='';save('sharedText','');renderHome();loadHome()}if(action==='copy-share-address'){try{await navigator.clipboard.writeText(location.origin+'/#share?text=');toast('Address copied')}catch{$('#shareaddress').select();toast('Select and copy the address')}}if(action==='usage')openUsage();if(action==='usage-refresh'){refreshUsage(true);renderUsage()}if(action==='filters')openFilters();if(action==='sort')openSort();if(action==='close')sheet.close();if(action==='refresh')refresh();if(action==='more'){b.disabled=true;b.textContent='Loading…';loadHome({more:true})}
 if(action==='back')goBack();
 if(action==='jump'){const m=$('#messages');m.scrollTo({top:m.scrollHeight,behavior:'smooth'})}
 if(action==='reset'){if(tab==='threads')filters=defaults();else taskFilters=taskDefaults();sheet.close();renderHome();changed()}
 if(action==='saveview'){const name=$('#viewname').value.trim();if(!name){toast('Give this view a name');$('#viewname').focus();return}applyForm();views.push({name,filters:{...filters}});save('views',views);sheet.close();changed();toast('View saved')}
 if(action==='older')older();if(action==='delivery')checkDelivery();if(action==='dismissdelivery'){delete pending[threadId];save('pending',pending);renderThread()}
 if(action==='threadmenu')openThreadMenu(threadId);
 if(action==='markread'){try{await api(`thread/${threadId}/read`,{});sheet.close();toast('Marked as read')}catch(e){toast(e.message)}}
 if(action==='stop'){b.disabled=true;try{await api(`thread/${threadId}/stop`,{});sheet.close();await refreshThread();toast('Stop requested')}catch(e){toast(e.message);b.disabled=false}}
});
// Enter sends on hardware keyboards; on touch devices Enter adds a new line.
document.addEventListener('keydown',e=>{if(e.target.id==='draft'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&matchMedia('(hover:hover) and (pointer:fine)').matches){e.preventDefault();$('#compose').requestSubmit()}});

/* ---------- Gestures: pull to refresh, edge swipe back, compact FAB ---------- */
let pull=null;
document.addEventListener('touchstart',e=>{const t=e.touches[0];if(document.body.dataset.view!=='home'&&t.clientX<24){pull={edge:true,x:t.clientX,y:t.clientY,dx:0};return}if(document.body.dataset.view==='home'&&window.scrollY<=0&&!sheet.open&&!e.target.closest('.chips'))pull={x:t.clientX,y:t.clientY,dy:0}},{passive:true});
document.addEventListener('touchmove',e=>{if(!pull)return;const t=e.touches[0];if(pull.edge){pull.dx=t.clientX-pull.x;const v=document.querySelector('.threadview,.taskdetail');if(v&&pull.dx>0&&Math.abs(t.clientY-pull.y)<60){v.style.transform=`translateX(${pull.dx*.6}px)`;v.style.transition='none'}return}pull.dy=t.clientY-pull.y;if(Math.abs(t.clientX-pull.x)>Math.abs(pull.dy)){pull=null;return}const ptr=$('.ptr');if(ptr&&pull.dy>0){const y=Math.min(80,pull.dy*.45);ptr.style.transform=`translate(-50%,${y}px) rotate(${y*4}deg)`;ptr.style.opacity=Math.min(1,y/50);ptr.classList.toggle('armed',y>=60)}},{passive:true});
document.addEventListener('touchend',async()=>{if(!pull)return;const p=pull;pull=null;if(p.edge){const v=document.querySelector('.threadview,.taskdetail');if(v){v.style.transition='';v.style.transform=''}if(p.dx>90)goBack();return}const ptr=$('.ptr');if(!ptr)return;if(ptr.classList.contains('armed')){ptr.classList.add('spinning');ptr.style.transform='translate(-50%,56px)';try{await refresh()}finally{ptr.classList.remove('spinning','armed');ptr.style.transform='';ptr.style.opacity=''}}else{ptr.style.transform='';ptr.style.opacity=''}},{passive:true});
document.addEventListener('touchcancel',()=>{pull=null;const v=document.querySelector('.threadview,.taskdetail');if(v){v.style.transition='';v.style.transform=''}const ptr=$('.ptr');if(ptr&&!ptr.classList.contains('spinning')){ptr.style.transform='';ptr.style.opacity='';ptr.classList.remove('armed')}},{passive:true});
let lastY=0;window.addEventListener('scroll',()=>{const y=window.scrollY;document.body.classList.toggle('scrolled',y>8);const fab=$('.fab');if(fab)fab.classList.toggle('compact',y>lastY&&y>120);lastY=y},{passive:true});

window.addEventListener('popstate',handleRoute);window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#share?'))handleRoute()});window.addEventListener('online',()=>{syncText('Reconnecting');refresh()});window.addEventListener('offline',()=>syncText('Offline · saved',true));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('pageshow',e=>{if(e.persisted)refresh()});
// Track the visual viewport so the composer stays above the iOS keyboard.
function viewport(){const v=window.visualViewport;const height=v?.height||innerHeight;document.documentElement.style.setProperty('--app-height',height+'px');document.documentElement.style.setProperty('--app-top',(v?.offsetTop||0)+'px');const keyboard=innerHeight-height>120;document.documentElement.style.setProperty('--keyboard-inset',keyboard?'0px':'env(safe-area-inset-bottom)');document.body.classList.toggle('keyboard',keyboard)}
window.visualViewport?.addEventListener('resize',viewport);window.visualViewport?.addEventListener('scroll',viewport);window.addEventListener('resize',viewport);document.addEventListener('focusin',viewport);document.addEventListener('focusout',()=>requestAnimationFrame(viewport));viewport();
async function tick(){if(!document.hidden){refreshUsage();try{if(threadId)await refreshThread();else if(!route.startsWith('task/')&&tab!=='projects')await loadHome()}catch{}}pollTimer=setTimeout(tick,threadId?3000:15000)}
async function init(){meta=await get('meta')||meta;usage=await get('usage');if(usage)usage={...usage,stale:true};handleRoute();refreshUsage(true);await refreshMeta();tick();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}init();
