import {marked} from 'marked';
import DOMPurify from 'dompurify';
import {get,put,read,save} from './storage.js';
const $=s=>document.querySelector(s),app=$('#app'),sheet=$('#sheet');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={threads:'M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2v-10a8.5 8.5 0 0 1 17 0M7 10h8M7 14h5',tasks:'m8 6 2 2 4-4M8 16l2 2 4-4M18 7h3M18 17h3M3 3v18',projects:'M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z',search:'m21 21-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',filter:'M4 7h16M4 17h16M8 4v6M16 14v6',back:'m15 5-7 7 7 7',send:'M12 20V4m-7 7 7-7 7 7',refresh:'M20 7v5h-5M4 17v-5h5M6 6a8 8 0 0 1 13 2M18 18a8 8 0 0 1-13-2',close:'m6 6 12 12M6 18 18 6',more:'M5 12h.01M12 12h.01M19 12h.01'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.threads}"/></svg>`;
const defaults=()=>({q:'',project:'',status:'',include:'',exclude:'automation',unread:'false',sort:'recent'});
let filters=read('filters',defaults()),taskFilters=read('taskFilters',{q:'',project:'',status:''});
let tab=read('tab','threads'),meta={projects:[],taskProjects:[],labels:[]},data=null,route='',threadId=null,threadData=null,olderRows=[],olderCursor=null,threadReady=false,epoch=0,loading=false,online=navigator.onLine,connection='Connecting',error='',pollTimer,searchTimer,listScroll=0,loadingOlder=false;
let usage=null,usageError='',usagePending=false,usageChecked=0;
let views=read('views',[]),pending=read('pending',{}),renderedRows='';
for(const p of Object.values(pending))if(p.state==='sending')p.state='unknown';
const now=()=>Date.now();const relative=t=>{const n=Math.max(0,(now()-new Date(t).getTime())/60000);return n<1?'now':n<60?Math.floor(n)+'m':n<1440?Math.floor(n/60)+'h':n<10080?Math.floor(n/1440)+'d':new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric'})};
const bbUrl=()=>{try{const u=new URL(meta.bbUrl||location.origin);return ['http:','https:'].includes(u.protocol)?esc(u.href):'/'}catch{return '/'}};
const pname=id=>meta.projects.find(p=>p.id===id)?.name||'Personal';
const tname=id=>meta.taskProjects.find(p=>p.id===id)?.name||'Tasks';
const pretty=s=>(s||'').replaceAll('_',' ');
function md(text){return DOMPurify.sanitize(marked.parse(text||'',{breaks:true}),{FORBID_TAGS:['style','form','input','button','iframe'],FORBID_ATTR:['style']})}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}
async function api(path,body){const res=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json','x-pocket-request':'1'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(25000),cache:'no-store'});if(res.redirected||!res.headers.get('content-type')?.includes('application/json'))throw new Error('Sign in to BB Connect to reconnect');const d=await res.json();if(!res.ok)throw new Error(d.error||'Request failed');return d}
function syncText(text,isOffline=false){connection=text;for(const el of document.querySelectorAll('.sync')){el.classList.toggle('offline',isOffline);el.innerHTML=`<span class="dot"></span>${esc(text)}`}}
function usageHtml(){
 const providers=Object.entries(usage?.providers||{}).filter(([,p])=>p.status!=='not_installed');
 const counters=providers.flatMap(([id,p])=>p.status==='ok'?(p.windows||[]).map(w=>`${id} ${w.label}: ${Number.isFinite(w.usedPercent)?Math.round(w.usedPercent)+'%':'unknown'}`):[]);
 return `<details class="usage" ${read('usageOpen',false)?'open':''}><summary>Usage limits <span>${esc(counters.length?counters.slice(0,2).join(' · '):usageError?'Unavailable':usage?'No counters reported':'Loading…')}</span></summary><div class="usagebody">${usageError||usage?.stale?'<p class="muted">Saved usage · '+esc(usageError||'refreshing')+'</p>':''}${providers.map(([id,p])=>`<section><strong>${esc(id)}</strong>${p.planLabel?` <small>${esc(p.planLabel)}</small>`:''}${p.status==='ok'?(p.windows?.length?p.windows.map(w=>{const n=Number.isFinite(w.usedPercent)?w.usedPercent:null;const date=w.resetsAt?new Date(w.resetsAt):null;return `<div class="usagewindow"><div>${esc(w.label)} <b>${n===null?'Unknown':Math.round(n)+'% used'}</b></div>${n===null?'':`<progress max="100" value="${Math.min(100,Math.max(0,n))}" aria-label="${esc(id+' '+w.label+' usage')}"></progress>`}<small>${date&&Number.isFinite(date.getTime())?'Resets '+esc(date.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})):'Reset time unavailable'}</small></div>`}).join(''):'<p class="muted">No usage windows reported.</p>'):`<p class="muted">${esc(p.status==='unauthenticated'?'Sign in through BB':p.status==='expired'?'Session expired — sign in through BB':'Usage unavailable')}</p>`}</section>`).join('')||'<p class="muted">No provider counters available.</p>'}${usage?.syncedAt?`<small>Updated ${esc(new Date(usage.syncedAt).toLocaleTimeString())}</small>`:''}<button class="secondary" data-action="usage-refresh">Refresh usage</button></div></details>`;
}
function renderUsage(){const el=$('#usagepanel');if(el)el.innerHTML=usageHtml()}
async function refreshUsage(force=false){if(usagePending||(!force&&Date.now()-usageChecked<60000))return;usagePending=true;usageChecked=Date.now();try{usage=await api('usage');usageError=usage.warning?'BB usage unavailable':'';put('usage',usage)}catch(e){usageError=navigator.onLine?e.message:'Offline';if(usage)usage.stale=true}finally{usagePending=false;renderUsage()}}
document.addEventListener('toggle',e=>{if(e.target.matches?.('.usage'))save('usageOpen',e.target.open)},true);
function nav(){return `<nav class="bottomnav" aria-label="Main navigation">${['threads','tasks','projects'].map(t=>`<button data-tab="${t}" class="${tab===t?'selected':''}" ${tab===t?'aria-current="page"':''}>${icon(t)}${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</nav>`}
function banner(){return error?`<div class="banner">${esc(error)} <button data-action="refresh">Retry</button> · <a href="${bbUrl()}" target="_blank" rel="noopener">BB login</a></div>`:''}
function chips(){if(tab==='tasks')return `${taskFilters.project?`<button class="chip" data-clear="project">${esc(tname(taskFilters.project))} <span class="x">×</span></button>`:''}${taskFilters.status?`<button class="chip" data-clear="status">${esc(pretty(taskFilters.status))} <span class="x">×</span></button>`:''}`;
 const labels=slug=>meta.labels.find(l=>l.slug===slug)?.name||slug;
 return ['exclude','include'].map(k=>filters[k].split(',').filter(Boolean).map(l=>`<button class="chip ${k}" data-rule="${k}" data-label="${esc(l)}">${k==='exclude'?'Exclude':'Include'}: ${esc(labels(l))} <span class="x">×</span></button>`).join('')).join('')+['project','status','unread'].filter(k=>filters[k]&&filters[k]!=='false').map(k=>`<button class="chip" data-clear="${k}">${esc(k==='project'?pname(filters[k]):k==='unread'?'Unread':pretty(filters[k]))} <span class="x">×</span></button>`).join('');
}
function renderHome(){threadId=null;threadReady=false;document.body.style.overflow='';const title=tab[0].toUpperCase()+tab.slice(1);app.innerHTML=`<main class="shell"><div class="masthead"><div class="brand"><span class="brandmark">b<span>b</span></span> Pocket</div><button class="sync" data-action="refresh" title="Refresh"><span class="dot"></span>${esc(connection)}</button></div><div class="heading"><div><p class="eyebrow">Your workspace, wherever</p><h1>${title}</h1></div><button class="iconbtn" data-action="refresh" aria-label="Refresh">${icon('refresh')}</button></div><div id="usagepanel">${usageHtml()}</div><div id="banner">${banner()}</div><div class="searchrow"><div class="search">${icon('search')}<input id="search" type="search" autocomplete="off" placeholder="Search ${tab}…" aria-label="Search ${tab}" value="${esc(tab==='threads'?filters.q:tab==='tasks'?taskFilters.q:'')}"></div>${tab!=='projects'?`<button class="iconbtn" data-action="filters" aria-label="Filters">${icon('filter')}</button>`:''}</div><div class="chips" id="chips">${tab==='projects'?'':chips()}</div><div id="results"></div></main>${nav()}`;renderResults();}
function renderResults(){const el=$('#results');if(!el||threadId)return;
 if(tab==='projects'){renderProjects();return}
 if(!data){el.innerHTML=Array.from({length:5},()=>'<div class="skeleton"></div>').join('');return}
 const rows=tab==='threads'?data.threads:data.tasks;
 el.innerHTML=`<div class="listhead"><span>${data.total.toLocaleString()} ${tab}${data.cached?' · saved on this device':''}</span><button data-action="filters">${tab==='threads'?(filters.sort==='oldest'?'Oldest first':filters.sort==='pinned'?'Pinned first':'Recent activity'):'Recently updated'} ↓</button></div><div class="rows">${rows.map(tab==='threads'?threadCard:taskCard).join('')}</div>${rows.length?'':`<div class="empty">No ${tab} match these filters.<br><button class="secondary" data-action="reset">Reset filters</button></div>`}${data.nextOffset!==null?'<button class="secondary loadmore" data-action="more">Load more</button>':''}`;
}
function threadCard(t){return `<button class="row ${t.unread?'unread':''}" data-thread="${esc(t.id)}"><div class="rowtop"><span class="statusdot ${esc(t.hasPendingInteraction?'attention':t.status)}"></span><span>${esc(pname(t.projectId))}</span>${t.unread?'<span class="unreadmark" aria-label="Unread"></span>':''}<time>${relative(t.updatedAt)}</time></div><div class="rowtitle">${esc(t.title)}</div><div class="rowfoot"><span>${t.hasPendingInteraction?'Needs input':esc(pretty(t.status))}</span>${(t.labels||[]).slice(0,2).map(l=>`<span class="tag">${esc(meta.labels.find(a=>a.slug===l)?.name||l)}</span>`).join('')}<span class="provider">${esc(t.providerId)}</span></div></button>`}
function taskCard(t){return `<button class="row" data-task="${esc(t.id)}"><div class="rowtop"><span class="statusdot ${esc(t.status)}"></span><span>${esc(t.key)} · ${esc(tname(t.projectId))}</span><time>${relative(t.updatedAt)}</time></div><div class="rowtitle">${esc(t.title)}</div><div class="rowfoot"><span>${esc(pretty(t.status))}</span>${t.priority!=='none'?`<span class="tag">${esc(t.priority)}</span>`:''}${t.dueDate?`<span>Due ${esc(t.dueDate)}</span>`:''}</div></button>`}
function renderProjects(){const query=($('#search')?.value||'').toLowerCase();$('#results').innerHTML=[['Task projects',meta.taskProjects,true],['BB projects',meta.projects,false]].map(([name,ps,task])=>`<div class="sectionlabel">${name} · ${ps.length}</div><div class="projectgrid">${ps.filter(p=>p.name.toLowerCase().includes(query)||(p.prefix||'').toLowerCase().includes(query)).map(p=>`<article class="projectcard"><div class="monogram">${esc((p.prefix||p.name.slice(0,2)).toUpperCase())}</div><h3>${esc(p.name)}</h3><div class="actions">${task?`<button data-project-tasks="${p.id}">Tasks ↗</button>`:''}${!task||p.linkedBbProjectId?`<button data-project-threads="${task?p.linkedBbProjectId:p.id}" ${task?`data-project-label="${esc(meta.labels.find(l=>l.name===p.name)?.slug||'')}"`:''}>Threads ↗</button>`:''}</div></article>`).join('')}</div>`).join('')}
function listKey(){return tab+'?'+new URLSearchParams(tab==='threads'?filters:taskFilters)}
async function loadHome({more=false}={}){
 if(threadId||tab==='projects')return;const requestEpoch=++epoch,key=listKey(),currentTab=tab;
 if(!more&&!data){const c=await get(key);if(epoch!==requestEpoch)return;if(c){data={...c,cached:true};renderResults();syncText('Saved · refreshing')}}
 try{const result=await api(key+(more?'&offset='+data.nextOffset:'&limit='+Math.max(60,data?.[currentTab]?.length||60)));if(epoch!==requestEpoch||threadId||tab!==currentTab)return;error='';data=more?{...result,[currentTab]:[...data[currentTab],...result[currentTab]]}:result;renderResults();error=result.warning?'BB is unavailable. Showing saved data.':'';$('#banner').innerHTML=banner();syncText(result.warning?'BB unavailable':result.stale?'Refreshing':'Up to date',!!result.warning);put(key,data)}catch(e){if(epoch!==requestEpoch)return;error=e.message;$('#banner')&&($('#banner').innerHTML=banner());syncText(navigator.onLine?'Reconnecting':'Offline · saved',true);if(!data){$('#results').innerHTML='<div class="empty">Couldn’t load your workspace.<br>Your filters and drafts are safe.</div>'}}
}
function changed(){save('filters',filters);save('taskFilters',taskFilters);data=null;$('#chips')&&($('#chips').innerHTML=chips());loadHome()}
function setTab(t){epoch++;tab=t;save('tab',tab);data=null;history.pushState({pocket:true},'', '#'+t);route=t;renderHome();loadHome();window.scrollTo(0,0)}
function option(value,label,current){return `<option value="${esc(value)}" ${current===value?'selected':''}>${esc(label)}</option>`}
function openFilters(){const f=tab==='threads'?filters:taskFilters;const thread=tab==='threads';sheet.innerHTML=`<div class="sheetinner"><div class="sheethead"><h2>Filter ${tab}</h2><button class="iconbtn" data-action="close" aria-label="Close">${icon('close')}</button></div><form id="filterform"><div class="field"><label for="projectfilter">Project</label><select id="projectfilter" name="project">${option('','All projects',f.project)}${(thread?meta.projects:meta.taskProjects).map(p=>option(p.id,p.name,f.project)).join('')}</select></div><div class="field"><label for="statusfilter">Status</label><select id="statusfilter" name="status">${option('','Any status',f.status)}${(thread?['running','attention','idle','error','pending']:['backlog','todo','in_progress','in_review','done','canceled']).map(s=>option(s,pretty(s),f.status)).join('')}</select></div>${thread?`<div class="field"><label for="unreadfilter">Read state</label><select id="unreadfilter" name="unread">${option('false','All threads',f.unread)}${option('true','Unread only',f.unread)}</select></div><div class="field"><label for="sortfilter">Sort</label><select id="sortfilter" name="sort">${option('recent','Recent activity',f.sort)}${option('oldest','Oldest first',f.sort)}${option('pinned','Pinned first',f.sort)}</select></div><div class="sectionlabel">Labels · combine include / exclude</div>${meta.labels.map(l=>`<div class="labelrule"><label for="label-${l.id}">${esc(l.name)}</label><select id="label-${l.id}" name="label:${l.slug}">${option('','Any',f.exclude.split(',').includes(l.slug)?'exclude':f.include.split(',').includes(l.slug)?'include':'')}${option('include','Include',f.include.split(',').includes(l.slug)?'include':'')}${option('exclude','Exclude',f.exclude.split(',').includes(l.slug)?'exclude':'')}</select></div>`).join('')}`:''}<div class="sheetfooter"><button type="button" class="secondary" data-action="reset">Reset</button><button class="primary" type="submit">Apply filters</button></div></form>${thread?`<div class="sectionlabel">Saved views</div><div class="field"><label for="viewname">Save current filters as a view</label><input id="viewname" placeholder="e.g. Running work"></div><button class="secondary" data-action="saveview">Save current view</button>${views.map((v,i)=>`<div class="savedview"><button class="secondary" data-view="${i}">${esc(v.name)}</button><button class="iconbtn" data-delete-view="${i}" aria-label="Delete ${esc(v.name)}">${icon('close')}</button></div>`).join('')}`:''}</div>`;sheet.showModal()}
function applyForm(){const f=Object.fromEntries(new FormData($('#filterform')));if(tab==='threads'){const include=[],exclude=[];for(const [k,v]of Object.entries(f))if(k.startsWith('label:')&&v)(v==='include'?include:exclude).push(k.slice(6));filters={...filters,project:f.project,status:f.status,unread:f.unread,sort:f.sort,include:include.join(','),exclude:exclude.join(',')}}else taskFilters={...taskFilters,project:f.project,status:f.status}}
function threadShell(id){document.body.style.overflow='hidden';const cachedTitle=data?.threads?.find(t=>t.id===id)?.title||'Conversation';app.innerHTML=`<section class="threadview"><header class="threadhead"><button class="iconbtn" data-action="back" aria-label="Back">${icon('back')}</button><div class="title"><h2 id="threadtitle">${esc(cachedTitle)}</h2><small id="threadsubtitle">Loading conversation…</small></div><button class="iconbtn" data-action="threadmenu" aria-label="Thread actions">${icon('more')}</button></header><div class="messages" id="messages"><div class="empty">Opening conversation…</div></div><div class="composer"><div class="composerstatus"><span class="sync"><span class="dot"></span>${esc(connection)}</span><button data-action="refresh">Refresh</button></div><form id="compose"><textarea id="draft" aria-label="Message" placeholder="Message your agent…" rows="1"></textarea><button type="submit" class="primary" aria-label="Send message">${icon('send')}</button></form></div></section>`;$('#draft').value=read('draft:'+id,'');$('#messages').addEventListener('scroll',()=>{const m=$('#messages');save('scroll:'+id,{top:m.scrollTop,bottom:m.scrollHeight-m.clientHeight-m.scrollTop<100})},{passive:true})}
async function openThread(id){epoch++;threadId=id;threadData=null;olderRows=[];olderCursor=null;threadReady=false;renderedRows='';threadShell(id);const c=await get('thread:'+id);if(threadId!==id)return;if(c){threadData=c;renderThread(true);syncText('Saved · refreshing')}await refreshThread(true);if(pending[id]&&threadId===id)checkDelivery()}
function rowHtml(r){if(r.kind==='conversation'){const role=r.role==='user'?'user':'assistant';return `<article class="message ${role}" id="row-${esc(r.id)}"><header><span>${role==='user'?'You':'Agent'}</span><span>${new Date(r.createdAt).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</span></header><div class="prose">${md(r.text)}</div>${r.attachments&&(r.attachments.localImages||r.attachments.localFiles||r.attachments.webImages)?'<p class="muted">Attachments available in BB</p>':''}</article>`}if(r.kind==='turn')return `<details class="activity"><summary>${r.status==='completed'?'Completed':'Agent '+esc(r.status)} · ${r.summaryCount||0} activity items</summary><p>Open BB for the full tool transcript.</p></details>`;if(r.kind==='system')return `<details class="activity"><summary>${esc(r.title||r.systemKind||'Status')}</summary><pre>${esc(r.detail||'')}</pre></details>`;return `<details class="activity"><summary>${esc(r.title||r.label||r.kind||'Agent activity')}</summary><pre>${esc(r.text||r.detail||r.status||'')}</pre></details>`}
function timelineHtml(rows){let html='',group=[];const flush=()=>{if(!group.length)return;html+=`<details class="activity"><summary>${group.length} agent activities · ${group.some(r=>r.status==='pending')?'working':'completed'}</summary>${group.map(r=>`<details><summary>${esc(r.command?.split('\n')[0]?.slice(0,100)||r.title||r.workKind||r.kind)}</summary><pre>${esc(r.output||r.text||r.detail||r.status||'')}</pre></details>`).join('')}</details>`;group=[]};for(const r of rows){if(r.kind==='work'||r.kind==='thinking')group.push(r);else{flush();html+=rowHtml(r)}}flush();return html}
function deliveryHtml(){const p=pending[threadId];if(!p)return '';const label=p.state==='sent'?'Sent to BB':p.state==='sending'?'Sending…':p.state==='missing'?'Not submitted — draft saved':'Delivery unconfirmed — check the conversation before sending again.';return `<div class="delivery"><p>${esc(p.text.slice(0,160))}</p><p class="muted">${label}</p>${p.state!=='sending'?'<button data-action="delivery">Check delivery</button><button data-action="dismissdelivery">Dismiss</button>':''}</div>`}
function renderThread(initial=false){if(!threadData||!threadId)return;const t=threadData.thread;$('#threadtitle').textContent=t.title||t.titleFallback||'Conversation';$('#threadsubtitle').textContent=`${pname(t.projectId)} · ${pretty(t.status)} · ${t.providerId}`;
 const rows=[...new Map([...olderRows,...threadData.rows].map(r=>[r.id,r])).values()].sort((a,b)=>a.sourceSeqStart-b.sourceSeqStart);
 const html=`${olderCursor||threadData.timelinePage?.hasOlderRows?'<button class="secondary loadmore" data-action="older">Load earlier messages</button>':''}${timelineHtml(rows)}${t.status==='active'?'<div class="activity">Agent is working…</div>':''}${t.hasPendingInteraction?`<div class="banner">Your agent needs input. <a href="${bbUrl()}" target="_blank" rel="noopener">Open BB to respond</a></div>`:''}${deliveryHtml()}`;
 if(html===renderedRows)return;renderedRows=html;const m=$('#messages'),oldTop=m.scrollTop,oldHeight=m.scrollHeight,atBottom=oldHeight-m.clientHeight-oldTop<100,opened=[...m.querySelectorAll('details[open]')].map(e=>e.querySelector('summary')?.textContent);m.innerHTML=html;for(const d of m.querySelectorAll('details'))if(opened.includes(d.querySelector('summary')?.textContent))d.open=true;
 if(initial&&!threadReady){const pos=read('scroll:'+threadId,null);m.scrollTop=pos&&!pos.bottom?pos.top:m.scrollHeight;threadReady=true}else if(loadingOlder)m.scrollTop=oldTop+(m.scrollHeight-oldHeight);else m.scrollTop=atBottom?m.scrollHeight:oldTop;
}
async function refreshThread(initial=false){const id=threadId;if(!id)return;try{const d=await api(`thread/${id}/timeline`);if(threadId!==id)return;threadData=d;error='';renderThread(initial);syncText('Connected');put('thread:'+id,d)}catch(e){if(threadId!==id)return;syncText(navigator.onLine?'Reconnecting':'Offline · saved',true);if(!threadData)$('#messages').innerHTML=`<div class="empty">${esc(e.message)}<br><button class="secondary" data-action="refresh">Retry</button></div>`}}
async function older(){if(loadingOlder)return;loadingOlder=true;const id=threadId;try{const cursor=olderCursor||threadData.timelinePage?.olderCursor;if(!cursor)return;const d=await api(`thread/${id}/timeline?`+new URLSearchParams({beforeAnchorSeq:cursor.anchorSeq,beforeAnchorId:cursor.anchorId}));if(threadId!==id)return;olderRows=[...d.rows,...olderRows];olderCursor=d.timelinePage?.olderCursor||null;if(!d.timelinePage?.hasOlderRows)threadData.timelinePage.hasOlderRows=false;renderThread()}catch(e){toast(e.message)}finally{loadingOlder=false}}
async function sendMessage(){const id=threadId,text=$('#draft').value.trim();if(!text)return;if(!navigator.onLine){toast('Offline. Your draft is saved.');return}if(pending[id]&&pending[id].state!=='sent'){toast('Check the previous message’s delivery first.');return}const record={id:crypto.randomUUID(),text,state:'sending'};pending[id]=record;save('pending',pending);$('#compose button').disabled=true;renderThread();try{const result=await api(`thread/${id}/send`,record);record.state=result.state;if(result.state==='sent'){save('draft:'+id,'');if(threadId===id){$('#draft').value='';$('#draft').style.height='auto'}toast('Message sent')}else toast('Delivery unconfirmed. Check the conversation.')}catch{record.state='unknown';toast('Connection interrupted. Checking delivery is safe.')}finally{pending[id]=record;save('pending',pending);if(threadId===id){$('#compose button').disabled=false;await refreshThread();}}}
async function checkDelivery(){const id=threadId,p=pending[id];if(!p)return;try{const d=await api(`thread/${id}/delivery?id=${p.id}`);p.state=d.state;save('pending',pending);if(d.state==='sent'){save('draft:'+id,'');if(threadId===id)$('#draft').value='';toast('BB received your message')}else toast(d.state==='missing'?'Message was not submitted. You can dismiss and send your draft.':'Delivery still unconfirmed. Check the conversation.');if(threadId===id)renderThread()}catch(e){toast(e.message)}}
async function openTask(id){epoch++;threadId=null;document.body.style.overflow='';app.innerHTML=`<main class="taskdetail"><button class="iconbtn" data-action="back" aria-label="Back">${icon('back')}</button><div id="taskcontent"><div class="empty">Opening task…</div></div></main>`;const path='task/'+id,c=await get(path);if(route!==path)return;if(c)renderTask(c);try{const d=await api(path);if(route!==path)return;renderTask(d);put(path,d)}catch(e){toast(e.message)}}
function renderTask(d){if(!d.task){$('#taskcontent').innerHTML='<div class="empty">Task not found</div>';return}const t=d.task;$('#taskcontent').innerHTML=`<p class="sectionlabel">${esc(t.key)} · ${esc(tname(t.projectId))}</p><h1>${esc(t.title)}</h1><div class="chips"><span class="chip">${esc(pretty(t.status))}</span><span class="chip">${esc(t.priority)} priority</span></div><div class="prose">${md(t.description)}</div><div class="sectionlabel">Linked threads</div>${(d.taskThreads||[]).map(t=>`<button class="row" data-thread="${esc(t.threadId)}"><span class="rowtitle">${esc(t.title||t.threadId)}</span><span class="muted"> ${esc(t.status)}</span></button>`).join('')||'<p class="muted">No linked threads</p>'}<div class="sectionlabel">Comments · ${d.comments.length}</div>${d.comments.map(c=>`<article class="comment"><small>${esc(c.authorName)} · ${relative(c.createdAt)}</small><div class="prose">${md(c.body)}</div></article>`).join('')}`}
function navigate(hash){history.pushState({pocket:true},'','#'+hash);handleRoute()}
function handleRoute(){epoch++;route=location.hash.slice(1)||tab;if(route.startsWith('thread/')){openThread(route.slice(7));return}if(route.startsWith('task/')){openTask(route.slice(5));return}tab=['threads','tasks','projects'].includes(route)?route:'threads';threadId=null;data=null;renderHome();loadHome();requestAnimationFrame(()=>window.scrollTo(0,listScroll))}
async function refresh(){refreshUsage(true);if(threadId)return refreshThread();if(route.startsWith('task/'))return openTask(route.slice(5));await refreshMeta();await loadHome()}
async function refreshMeta(){try{const d=await api('meta');meta=d;await put('meta',d);if(!threadId&&!route.startsWith('task/')){if(tab==='projects')renderProjects();else{renderResults();$('#chips').innerHTML=chips()}}}catch(e){syncText('Reconnecting',true)}}
document.addEventListener('input',e=>{if(e.target.id==='search'){if(tab==='projects'){renderProjects();return}const f=tab==='threads'?filters:taskFilters;f.q=e.target.value;save(tab==='threads'?'filters':'taskFilters',f);clearTimeout(searchTimer);searchTimer=setTimeout(()=>{data=null;loadHome()},200)}if(e.target.id==='draft'){if(!save('draft:'+threadId,e.target.value))toast('Device storage is full; draft cannot be saved');e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,160)+'px'}});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='filterform'){applyForm();sheet.close();changed()}if(e.target.id==='compose')sendMessage()});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.tab){listScroll=0;setTab(d.tab)}
 if(d.thread){listScroll=window.scrollY;navigate('thread/'+d.thread)}if(d.task){listScroll=window.scrollY;navigate('task/'+d.task)}
 if(d.rule){filters[d.rule]=filters[d.rule].split(',').filter(l=>l!==d.label).join(',');changed()}
 if(d.clear){(tab==='threads'?filters:taskFilters)[d.clear]=d.clear==='unread'?'false':'';changed()}
 if(d.projectTasks){taskFilters.project=d.projectTasks;save('taskFilters',taskFilters);setTab('tasks')}
 if(d.projectThreads){filters.project=d.projectThreads;if(d.projectLabel!==undefined)filters.include=d.projectLabel;save('filters',filters);setTab('threads')}
 if(d.view!==undefined){filters={...views[Number(d.view)].filters};sheet.close();renderHome();changed()}
 if(d.deleteView!==undefined){views.splice(Number(d.deleteView),1);save('views',views);sheet.close();openFilters()}
 const action=d.action;if(action==='usage-refresh')refreshUsage(true);if(action==='filters')openFilters();if(action==='close')sheet.close();if(action==='refresh')refresh();if(action==='more'){b.disabled=true;loadHome({more:true})}
 if(action==='back'){if(history.state?.pocket)history.back();else navigate(tab)}
 if(action==='reset'){if(tab==='threads')filters=defaults();else taskFilters={q:'',project:'',status:''};sheet.close();renderHome();changed()}
 if(action==='saveview'){const name=$('#viewname').value.trim();if(!name){toast('Give this view a name');return}applyForm();views.push({name,filters:{...filters}});save('views',views);sheet.close();changed();toast('View saved')}
 if(action==='older')older();if(action==='delivery')checkDelivery();if(action==='dismissdelivery'){delete pending[threadId];save('pending',pending);renderThread()}
 if(action==='threadmenu'){sheet.innerHTML=`<div class="sheetinner"><div class="sheethead"><h2>Conversation</h2><button class="iconbtn" data-action="close" aria-label="Close">${icon('close')}</button></div><button class="secondary loadmore" data-action="markread">Mark as read</button><button class="secondary loadmore" data-action="stop">Stop agent</button><a class="secondary loadmore" href="${bbUrl()}" target="_blank" rel="noopener">Open full BB</a><p class="muted">Full BB includes approvals, attachments and model controls.</p></div>`;sheet.showModal()}
 if(action==='markread'){try{await api(`thread/${threadId}/read`,{});sheet.close();toast('Marked as read')}catch(e){toast(e.message)}}
 if(action==='stop'){b.disabled=true;try{await api(`thread/${threadId}/stop`,{});sheet.close();await refreshThread();toast('Stop requested')}catch(e){toast(e.message);b.disabled=false}}
});
window.addEventListener('popstate',handleRoute);window.addEventListener('online',()=>{syncText('Reconnecting');refresh()});window.addEventListener('offline',()=>syncText('Offline · saved',true));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('pageshow',e=>{if(e.persisted)refresh()});
function viewport(){document.documentElement.style.setProperty('--app-height',(window.visualViewport?.height||innerHeight)+'px')}window.visualViewport?.addEventListener('resize',viewport);viewport();
async function tick(){if(!document.hidden){refreshUsage();try{if(threadId)await refreshThread();else if(!route.startsWith('task/')&&tab!=='projects')await loadHome()}catch{}}pollTimer=setTimeout(tick,threadId?3000:15000)}
async function init(){meta=await get('meta')||meta;usage=await get('usage');if(usage)usage={...usage,stale:true};handleRoute();refreshUsage(true);await refreshMeta();tick();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}init();
